// Code generated by go-enum
// DO NOT EDIT!

package config

import (
	"fmt"
	"strings"
)

const (
	// SSLTypeNone is a SSLType of type None.
	SSLTypeNone SSLType = iota
	// SSLTypeStatis is a SSLType of type Statis.
	SSLTypeStatis
	// SSLTypeAuto is a SSLType of type Auto.
	SSLTypeAuto
)

const _SSLTypeName = "nonestatisauto"

var _SSLTypeNames = []string{
	_SSLTypeName[0:4],
	_SSLTypeName[4:10],
	_SSLTypeName[10:14],
}

// SSLTypeNames returns a list of possible string values of SSLType.
func SSLTypeNames() []string {
	tmp := make([]string, len(_SSLTypeNames))
	copy(tmp, _SSLTypeNames)
	return tmp
}

var _SSLTypeMap = map[SSLType]string{
	0: _SSLTypeName[0:4],
	1: _SSLTypeName[4:10],
	2: _SSLTypeName[10:14],
}

// String implements the Stringer interface.
func (x SSLType) String() string {
	if str, ok := _SSLTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SSLType(%d)", x)
}

var _SSLTypeValue = map[string]SSLType{
	_SSLTypeName[0:4]:                    0,
	strings.ToLower(_SSLTypeName[0:4]):   0,
	_SSLTypeName[4:10]:                   1,
	strings.ToLower(_SSLTypeName[4:10]):  1,
	_SSLTypeName[10:14]:                  2,
	strings.ToLower(_SSLTypeName[10:14]): 2,
}

// ParseSSLType attempts to convert a string to a SSLType
func ParseSSLType(name string) (SSLType, error) {
	if x, ok := _SSLTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _SSLTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return SSLType(0), fmt.Errorf("%s is not a valid SSLType, try [%s]", name, strings.Join(_SSLTypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x SSLType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *SSLType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseSSLType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// StoreTypeSqlite is a StoreType of type Sqlite.
	StoreTypeSqlite StoreType = iota
	// StoreTypeMysql is a StoreType of type Mysql.
	StoreTypeMysql
	// StoreTypePostgres is a StoreType of type Postgres.
	StoreTypePostgres
)

const _StoreTypeName = "sqlitemysqlpostgres"

var _StoreTypeNames = []string{
	_StoreTypeName[0:6],
	_StoreTypeName[6:11],
	_StoreTypeName[11:19],
}

// StoreTypeNames returns a list of possible string values of StoreType.
func StoreTypeNames() []string {
	tmp := make([]string, len(_StoreTypeNames))
	copy(tmp, _StoreTypeNames)
	return tmp
}

var _StoreTypeMap = map[StoreType]string{
	0: _StoreTypeName[0:6],
	1: _StoreTypeName[6:11],
	2: _StoreTypeName[11:19],
}

// String implements the Stringer interface.
func (x StoreType) String() string {
	if str, ok := _StoreTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("StoreType(%d)", x)
}

var _StoreTypeValue = map[string]StoreType{
	_StoreTypeName[0:6]:                    0,
	strings.ToLower(_StoreTypeName[0:6]):   0,
	_StoreTypeName[6:11]:                   1,
	strings.ToLower(_StoreTypeName[6:11]):  1,
	_StoreTypeName[11:19]:                  2,
	strings.ToLower(_StoreTypeName[11:19]): 2,
}

// ParseStoreType attempts to convert a string to a StoreType
func ParseStoreType(name string) (StoreType, error) {
	if x, ok := _StoreTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _StoreTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return StoreType(0), fmt.Errorf("%s is not a valid StoreType, try [%s]", name, strings.Join(_StoreTypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x StoreType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *StoreType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStoreType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
