// Code generated by go-enum
// DO NOT EDIT!

package config

import (
	"fmt"
	"strings"
)

const (
	// SSLModeNone is a SSLMode of type None.
	SSLModeNone SSLMode = iota
	// SSLModeStatic is a SSLMode of type Static.
	SSLModeStatic
	// SSLModeAuto is a SSLMode of type Auto.
	SSLModeAuto
)

const _SSLModeName = "nonestaticauto"

var _SSLModeNames = []string{
	_SSLModeName[0:4],
	_SSLModeName[4:10],
	_SSLModeName[10:14],
}

// SSLModeNames returns a list of possible string values of SSLMode.
func SSLModeNames() []string {
	tmp := make([]string, len(_SSLModeNames))
	copy(tmp, _SSLModeNames)
	return tmp
}

var _SSLModeMap = map[SSLMode]string{
	0: _SSLModeName[0:4],
	1: _SSLModeName[4:10],
	2: _SSLModeName[10:14],
}

// String implements the Stringer interface.
func (x SSLMode) String() string {
	if str, ok := _SSLModeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SSLMode(%d)", x)
}

var _SSLModeValue = map[string]SSLMode{
	_SSLModeName[0:4]:                    0,
	strings.ToLower(_SSLModeName[0:4]):   0,
	_SSLModeName[4:10]:                   1,
	strings.ToLower(_SSLModeName[4:10]):  1,
	_SSLModeName[10:14]:                  2,
	strings.ToLower(_SSLModeName[10:14]): 2,
}

// ParseSSLMode attempts to convert a string to a SSLMode
func ParseSSLMode(name string) (SSLMode, error) {
	if x, ok := _SSLModeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _SSLModeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return SSLMode(0), fmt.Errorf("%s is not a valid SSLMode, try [%s]", name, strings.Join(_SSLModeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x SSLMode) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *SSLMode) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseSSLMode(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// StoreTypeSqlite is a StoreType of type Sqlite.
	StoreTypeSqlite StoreType = iota
	// StoreTypeMysql is a StoreType of type Mysql.
	StoreTypeMysql
	// StoreTypePostgres is a StoreType of type Postgres.
	StoreTypePostgres
)

const _StoreTypeName = "sqlitemysqlpostgres"

var _StoreTypeNames = []string{
	_StoreTypeName[0:6],
	_StoreTypeName[6:11],
	_StoreTypeName[11:19],
}

// StoreTypeNames returns a list of possible string values of StoreType.
func StoreTypeNames() []string {
	tmp := make([]string, len(_StoreTypeNames))
	copy(tmp, _StoreTypeNames)
	return tmp
}

var _StoreTypeMap = map[StoreType]string{
	0: _StoreTypeName[0:6],
	1: _StoreTypeName[6:11],
	2: _StoreTypeName[11:19],
}

// String implements the Stringer interface.
func (x StoreType) String() string {
	if str, ok := _StoreTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("StoreType(%d)", x)
}

var _StoreTypeValue = map[string]StoreType{
	_StoreTypeName[0:6]:                    0,
	strings.ToLower(_StoreTypeName[0:6]):   0,
	_StoreTypeName[6:11]:                   1,
	strings.ToLower(_StoreTypeName[6:11]):  1,
	_StoreTypeName[11:19]:                  2,
	strings.ToLower(_StoreTypeName[11:19]): 2,
}

// ParseStoreType attempts to convert a string to a StoreType
func ParseStoreType(name string) (StoreType, error) {
	if x, ok := _StoreTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _StoreTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return StoreType(0), fmt.Errorf("%s is not a valid StoreType, try [%s]", name, strings.Join(_StoreTypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x StoreType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *StoreType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStoreType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
