// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"

	"github.com/filebrowser/filebrowser/v3/store/sql/ent/mount"
)

// Mount is the model entity for the Mount schema.
type Mount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MountQuery when eager-loading is set.
	Edges MountEdges `json:"edges"`
}

// MountEdges holds the relations/edges for other nodes in the graph.
type MountEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e MountEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e MountEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[1] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mount) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case mount.FieldID:
			values[i] = new(sql.NullInt64)
		case mount.FieldName, mount.FieldPath:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Mount", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mount fields.
func (m *Mount) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int(value.Int64)
		case mount.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				m.Name = value.String
			}
		case mount.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				m.Path = value.String
			}
		}
	}
	return nil
}

// QueryUsers queries the "users" edge of the Mount entity.
func (m *Mount) QueryUsers() *UserQuery {
	return (&MountClient{config: m.config}).QueryUsers(m)
}

// QueryGroups queries the "groups" edge of the Mount entity.
func (m *Mount) QueryGroups() *GroupQuery {
	return (&MountClient{config: m.config}).QueryGroups(m)
}

// Update returns a builder for updating this Mount.
// Note that you need to call Mount.Unwrap() before calling this method if this Mount
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Mount) Update() *MountUpdateOne {
	return (&MountClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the Mount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Mount) Unwrap() *Mount {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Mount is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Mount) String() string {
	var builder strings.Builder
	builder.WriteString("Mount(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", name=")
	builder.WriteString(m.Name)
	builder.WriteString(", path=")
	builder.WriteString(m.Path)
	builder.WriteByte(')')
	return builder.String()
}

// Mounts is a parsable slice of Mount.
type Mounts []*Mount

func (m Mounts) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
