// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/filebrowser/filebrowser/v3/store/sql/ent/group"
	"github.com/filebrowser/filebrowser/v3/store/sql/ent/mount"
	"github.com/filebrowser/filebrowser/v3/store/sql/ent/user"
)

// MountCreate is the builder for creating a Mount entity.
type MountCreate struct {
	config
	mutation *MountMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mc *MountCreate) SetName(s string) *MountCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetPath sets the "path" field.
func (mc *MountCreate) SetPath(s string) *MountCreate {
	mc.mutation.SetPath(s)
	return mc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (mc *MountCreate) AddUserIDs(ids ...string) *MountCreate {
	mc.mutation.AddUserIDs(ids...)
	return mc
}

// AddUsers adds the "users" edges to the User entity.
func (mc *MountCreate) AddUsers(u ...*User) *MountCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return mc.AddUserIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (mc *MountCreate) AddGroupIDs(ids ...int) *MountCreate {
	mc.mutation.AddGroupIDs(ids...)
	return mc
}

// AddGroups adds the "groups" edges to the Group entity.
func (mc *MountCreate) AddGroups(g ...*Group) *MountCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return mc.AddGroupIDs(ids...)
}

// Mutation returns the MountMutation object of the builder.
func (mc *MountCreate) Mutation() *MountMutation {
	return mc.mutation
}

// Save creates the Mount in the database.
func (mc *MountCreate) Save(ctx context.Context) (*Mount, error) {
	var (
		err  error
		node *Mount
	)
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MountCreate) SaveX(ctx context.Context) *Mount {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (mc *MountCreate) check() error {
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := mc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New("ent: missing required field \"path\"")}
	}
	if v, ok := mc.mutation.Path(); ok {
		if err := mount.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf("ent: validator failed for field \"path\": %w", err)}
		}
	}
	return nil
}

func (mc *MountCreate) sqlSave(ctx context.Context) (*Mount, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mc *MountCreate) createSpec() (*Mount, *sqlgraph.CreateSpec) {
	var (
		_node = &Mount{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: mount.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mount.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: mount.FieldName,
		})
		_node.Name = value
	}
	if value, ok := mc.mutation.Path(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: mount.FieldPath,
		})
		_node.Path = value
	}
	if nodes := mc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mount.UsersTable,
			Columns: mount.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mount.GroupsTable,
			Columns: mount.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: group.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MountCreateBulk is the builder for creating many Mount entities in bulk.
type MountCreateBulk struct {
	config
	builders []*MountCreate
}

// Save creates the Mount entities in the database.
func (mcb *MountCreateBulk) Save(ctx context.Context) ([]*Mount, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Mount, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MountCreateBulk) SaveX(ctx context.Context) []*Mount {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
