// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/filebrowser/filebrowser/v3/store/sql/ent/schema"
	"github.com/filebrowser/filebrowser/v3/store/sql/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
