version: '3'

includes:
  deps:
    taskfile: ../tools/Taskfile.yaml
    dir: ../tools

tasks:
  build:
    desc: Build backend

  lint:
    desc: Run linters
    cmds:
      - go tool golangci-lint run -v

  format:
    desc: Format code
    cmds:
      - go tool gofumpt -w .

  generate:
    desc: Run code generators
    cmds:
      - go generate ./...
      - go tool ogen --target api/gen -package gen --clean docs/openapi.yaml

  schema-inspect:
    desc: Inspect schema
    cmds:
      - atlas schema inspect -u "ent://storage/ent/schema" --dev-url "sqlite://file?mode=memory&_fk=1" --format '{{"{{"}} sql . "  " {{"}}"}}'

