// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Mount is the predicate function for mount builders.
type Mount func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
