// Code generated by entc, DO NOT EDIT.

package group

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeVolumes holds the string denoting the volumes edge name in mutations.
	EdgeVolumes = "volumes"
	// Table holds the table name of the group in the database.
	Table = "groups"
	// UsersTable is the table that holds the users relation/edge. The primary key declared below.
	UsersTable = "user_groups"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// VolumesTable is the table that holds the volumes relation/edge. The primary key declared below.
	VolumesTable = "group_volumes"
	// VolumesInverseTable is the table name for the Volume entity.
	// It exists in this package in order to avoid circular dependency with the "volume" package.
	VolumesInverseTable = "volumes"
)

// Columns holds all SQL columns for group fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// UsersPrimaryKey and UsersColumn2 are the table columns denoting the
	// primary key for the users relation (M2M).
	UsersPrimaryKey = []string{"user_id", "group_id"}
	// VolumesPrimaryKey and VolumesColumn2 are the table columns denoting the
	// primary key for the volumes relation (M2M).
	VolumesPrimaryKey = []string{"group_id", "volume_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
