// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"context"
	"fmt"
	"github.com/filebrowser/filebrowser/v3/auth"
	"github.com/filebrowser/filebrowser/v3/log"
	"github.com/filebrowser/filebrowser/v3/rest/api"
	"github.com/filebrowser/filebrowser/v3/service"
	"github.com/filebrowser/filebrowser/v3/service/filebrowser"
	"github.com/filebrowser/filebrowser/v3/store"
	"github.com/filebrowser/filebrowser/v3/store/sql"
	"github.com/filebrowser/filebrowser/v3/store/sql/ent"
	"github.com/filebrowser/filebrowser/v3/token"
	auth2 "github.com/go-pkgz/auth"
	"github.com/go-pkgz/auth/avatar"
	token2 "github.com/go-pkgz/auth/token"
	"github.com/google/wire"
	"github.com/pkg/errors"
	"github.com/spf13/afero"
	"path/filepath"
	"strings"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context, srvCmd *ServerCommand) (*serverApp, error) {
	fs := RootFSProvider(srvCmd)
	client, err := EntClientProvider(ctx, srvCmd)
	if err != nil {
		return nil, err
	}
	userStore := sql.NewUserStore(client)
	volumeStore := sql.NewVolumeStore(client)
	service := filebrowser.New(fs, userStore, volumeStore)
	authService := AuthServiceProvider(srvCmd, userStore)
	serverAuthRefreshCache := newAuthRefreshCache()
	service2, err := AuthenticatorProvider(srvCmd, authService, serverAuthRefreshCache)
	if err != nil {
		return nil, err
	}
	tokenService := TokenServiceProvider(srvCmd)
	sslConfig, err := NewSSLConfig(srvCmd)
	if err != nil {
		return nil, err
	}
	options := ApiServerOptionsProvider(srvCmd, sslConfig)
	server := api.NewServer(service, service2, tokenService, userStore, options)
	serverServerApp, err := NewServerApp(srvCmd, server)
	if err != nil {
		return nil, err
	}
	return serverServerApp, nil
}

// wire.go:

func EntClientProvider(ctx context.Context, srvCmd *ServerCommand) (client *ent.Client, err error) {
	switch srvCmd.Store.Type {
	case "sqlite":
		if err = makeDirs(filepath.Dir(srvCmd.Store.SQLite.File)); err != nil {
			return nil, errors.Wrap(err, "failed to create sqlite store")
		}
		client, err = ent.Open("sqlite3", fmt.Sprintf("file:%s?cache=shared&mode=rwc&_fk=1", srvCmd.Store.SQLite.File))
	case "postgres":
		client, err = ent.Open("postgres", srvCmd.Store.Postgres.DSN)
	case "mysql":
		client, err = ent.Open("mysql", srvCmd.Store.Postgres.DSN)
	default:
		return nil, errors.Errorf("unsupported store type %s", srvCmd.Store.Type)
	}
	if err != nil {
		return nil, errors.Wrap(err, "can't initialize data store")
	}
	log.WithContext(ctx).Debugf("Apply schema migrations")
	if err := client.Schema.Create(ctx); err != nil {
		return nil, err
	}

	return client, nil
}

var DataStoreSet = wire.NewSet(
	EntClientProvider, sql.NewUserStore, wire.Bind(new(store.UserStore), new(*sql.UserStore)), sql.NewVolumeStore, wire.Bind(new(store.VolumeStore), new(*sql.VolumeStore)),
)

var ServiceSet = wire.NewSet(filebrowser.New, wire.Bind(new(service.FileBrowser), new(*filebrowser.Service)))

func AuthServiceProvider(srvCmd *ServerCommand, userStore store.UserStore) *auth.Service {
	return auth.NewService(userStore, srvCmd.Auth.User.Home, srvCmd.Locale)
}

func TokenServiceProvider(srvCmd *ServerCommand) *token.Service {
	return token.New(srvCmd.Secret)
}

func ApiServerOptionsProvider(srvCmd *ServerCommand, sslConfig api.SSLConfig) api.Options {
	return api.Options{
		Host:         srvCmd.Host,
		Port:         srvCmd.Port,
		ServerURL:    srvCmd.ServerURL,
		SharedSecret: srvCmd.Secret,
		Revision:     srvCmd.Revision,
		AccessLog:    srvCmd.AccessLog.Enable,
		Anonymous:    srvCmd.Auth.Anonymous.Enable,
		SSLConfig:    sslConfig,
	}
}

func RootFSProvider(srvCmd *ServerCommand) afero.Fs {
	return afero.NewBasePathFs(afero.NewOsFs(), srvCmd.RootPath)
}

func AuthenticatorProvider(
	srvCmd *ServerCommand,
	authService *auth.Service, authRefreshCache2 *authRefreshCache,
) (*auth2.Service, error) {
	authenticator := auth2.NewService(auth2.Opts{
		DisableXSRF:    true,
		URL:            strings.TrimSuffix(srvCmd.ServerURL, "/"),
		Issuer:         "File Browser",
		TokenDuration:  srvCmd.Auth.TTL.JWT,
		CookieDuration: srvCmd.Auth.TTL.Cookie,
		SecureCookies:  strings.HasPrefix(srvCmd.ServerURL, "https://"),
		SecretReader: token2.SecretFunc(func(aud string) (string, error) {
			return srvCmd.Secret, nil
		}),
		ClaimsUpd:        authService,
		BasicAuthChecker: authService.BasicAuthChecker,
		Validator:        authService,
		AvatarStore:      avatar.NewNoOp(),
		Logger:           log.NewLogrAdapter(log.DefaultLogger),
		RefreshCache:     authRefreshCache2,
	})

	addAuthProviders(srvCmd, authenticator, authService)

	return authenticator, nil
}
