// Code generated by go-enum
// DO NOT EDIT!

package filesystem

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const (
	// TypeBlob is a Type of type Blob
	TypeBlob Type = iota
	// TypeVideo is a Type of type Video
	TypeVideo
	// TypeAudio is a Type of type Audio
	TypeAudio
	// TypeImage is a Type of type Image
	TypeImage
	// TypeText is a Type of type Text
	TypeText
	// TypeDir is a Type of type Dir
	TypeDir
)

const _TypeName = "blobvideoaudioimagetextdir"

var _TypeNames = []string{
	_TypeName[0:4],
	_TypeName[4:9],
	_TypeName[9:14],
	_TypeName[14:19],
	_TypeName[19:23],
	_TypeName[23:26],
}

// TypeNames returns a list of possible string values of Type.
func TypeNames() []string {
	tmp := make([]string, len(_TypeNames))
	copy(tmp, _TypeNames)
	return tmp
}

var _TypeMap = map[Type]string{
	0: _TypeName[0:4],
	1: _TypeName[4:9],
	2: _TypeName[9:14],
	3: _TypeName[14:19],
	4: _TypeName[19:23],
	5: _TypeName[23:26],
}

// String implements the Stringer interface.
func (x Type) String() string {
	if str, ok := _TypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Type(%d)", x)
}

var _TypeValue = map[string]Type{
	_TypeName[0:4]:                    0,
	strings.ToLower(_TypeName[0:4]):   0,
	_TypeName[4:9]:                    1,
	strings.ToLower(_TypeName[4:9]):   1,
	_TypeName[9:14]:                   2,
	strings.ToLower(_TypeName[9:14]):  2,
	_TypeName[14:19]:                  3,
	strings.ToLower(_TypeName[14:19]): 3,
	_TypeName[19:23]:                  4,
	strings.ToLower(_TypeName[19:23]): 4,
	_TypeName[23:26]:                  5,
	strings.ToLower(_TypeName[23:26]): 5,
}

// ParseType attempts to convert a string to a Type
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	return Type(0), fmt.Errorf("%s is not a valid Type, try [%s]", name, strings.Join(_TypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x Type) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Type) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Scan implements the Scanner interface.
func (x *Type) Scan(value interface{}) error {
	var name string

	switch v := value.(type) {
	case string:
		name = v
	case []byte:
		name = string(v)
	case nil:
		*x = Type(0)
		return nil
	}

	tmp, err := ParseType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Value implements the driver Valuer interface.
func (x Type) Value() (driver.Value, error) {
	return x.String(), nil
}
