// Code generated by go-enum
// DO NOT EDIT!

package filesystem

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// TypeFile is a Type of type File.
	TypeFile Type = iota
	// TypeDir is a Type of type Dir.
	TypeDir
	// TypeSpecial is a Type of type Special.
	TypeSpecial
)

const _TypeName = "filedirspecial"

var _TypeNames = []string{
	_TypeName[0:4],
	_TypeName[4:7],
	_TypeName[7:14],
}

// TypeNames returns a list of possible string values of Type.
func TypeNames() []string {
	tmp := make([]string, len(_TypeNames))
	copy(tmp, _TypeNames)
	return tmp
}

var _TypeMap = map[Type]string{
	0: _TypeName[0:4],
	1: _TypeName[4:7],
	2: _TypeName[7:14],
}

// String implements the Stringer interface.
func (x Type) String() string {
	if str, ok := _TypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Mode(%d)", x)
}

var _TypeValue = map[string]Type{
	_TypeName[0:4]:                   0,
	strings.ToLower(_TypeName[0:4]):  0,
	_TypeName[4:7]:                   1,
	strings.ToLower(_TypeName[4:7]):  1,
	_TypeName[7:14]:                  2,
	strings.ToLower(_TypeName[7:14]): 2,
}

// ParseType attempts to convert a string to a Type
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _TypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Type(0), fmt.Errorf("%s is not a valid Mode, try [%s]", name, strings.Join(_TypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x Type) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Type) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var _TypeErrNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Type) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Type(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Type(v)
	case string:
		*x, err = ParseType(v)
	case []byte:
		*x, err = ParseType(string(v))
	case Type:
		*x = v
	case int:
		*x = Type(v)
	case *Type:
		if v == nil {
			return _TypeErrNilPtr
		}
		*x = *v
	case uint:
		*x = Type(v)
	case uint64:
		*x = Type(v)
	case *int:
		if v == nil {
			return _TypeErrNilPtr
		}
		*x = Type(*v)
	case *int64:
		if v == nil {
			return _TypeErrNilPtr
		}
		*x = Type(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Type(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return _TypeErrNilPtr
		}
		*x = Type(*v)
	case *uint:
		if v == nil {
			return _TypeErrNilPtr
		}
		*x = Type(*v)
	case *uint64:
		if v == nil {
			return _TypeErrNilPtr
		}
		*x = Type(*v)
	case *string:
		if v == nil {
			return _TypeErrNilPtr
		}
		*x, err = ParseType(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Type) Value() (driver.Value, error) {
	return x.String(), nil
}
