// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldLockPassword holds the string denoting the lock_password field in the database.
	FieldLockPassword = "lock_password"
	// FieldBlocked holds the string denoting the blocked field in the database.
	FieldBlocked = "blocked"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldUsername,
	FieldPassword,
	FieldName,
	FieldScope,
	FieldLocale,
	FieldLockPassword,
	FieldBlocked,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScope holds the default value on creation for the "scope" field.
	DefaultScope string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
