// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldHome holds the string denoting the home field in the database.
	FieldHome = "home"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldLockPassword holds the string denoting the lock_password field in the database.
	FieldLockPassword = "lock_password"
	// FieldBlocked holds the string denoting the blocked field in the database.
	FieldBlocked = "blocked"
	// EdgeVolumes holds the string denoting the volumes edge name in mutations.
	EdgeVolumes = "volumes"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the user in the database.
	Table = "users"
	// VolumesTable is the table that holds the volumes relation/edge. The primary key declared below.
	VolumesTable = "user_volumes"
	// VolumesInverseTable is the table name for the Volume entity.
	// It exists in this package in order to avoid circular dependency with the "volume" package.
	VolumesInverseTable = "volumes"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "user_groups"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldUsername,
	FieldPassword,
	FieldHome,
	FieldName,
	FieldLocale,
	FieldLockPassword,
	FieldBlocked,
}

var (
	// VolumesPrimaryKey and VolumesColumn2 are the table columns denoting the
	// primary key for the volumes relation (M2M).
	VolumesPrimaryKey = []string{"user_id", "volume_id"}
	// GroupsPrimaryKey and GroupsColumn2 are the table columns denoting the
	// primary key for the groups relation (M2M).
	GroupsPrimaryKey = []string{"user_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
