// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/filebrowser/filebrowser/backend/storage/ent/backend"
)

// Backend is the model entity for the Backend schema.
type Backend struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Config holds the value of the "config" field.
	Config string `json:"config,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BackendQuery when eager-loading is set.
	Edges        BackendEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BackendEdges holds the relations/edges for other nodes in the graph.
type BackendEdges struct {
	// Volumes holds the value of the volumes edge.
	Volumes []*Volume `json:"volumes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VolumesOrErr returns the Volumes value or an error if the edge
// was not loaded in eager-loading.
func (e BackendEdges) VolumesOrErr() ([]*Volume, error) {
	if e.loadedTypes[0] {
		return e.Volumes, nil
	}
	return nil, &NotLoadedError{edge: "volumes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Backend) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backend.FieldID:
			values[i] = new(sql.NullInt64)
		case backend.FieldName, backend.FieldType, backend.FieldConfig:
			values[i] = new(sql.NullString)
		case backend.FieldCreateTime, backend.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Backend fields.
func (b *Backend) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backend.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			b.ID = int(value.Int64)
		case backend.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				b.CreateTime = value.Time
			}
		case backend.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				b.UpdateTime = value.Time
			}
		case backend.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				b.Name = value.String
			}
		case backend.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				b.Type = value.String
			}
		case backend.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				b.Config = value.String
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Backend.
// This includes values selected through modifiers, order, etc.
func (b *Backend) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// QueryVolumes queries the "volumes" edge of the Backend entity.
func (b *Backend) QueryVolumes() *VolumeQuery {
	return NewBackendClient(b.config).QueryVolumes(b)
}

// Update returns a builder for updating this Backend.
// Note that you need to call Backend.Unwrap() before calling this method if this Backend
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Backend) Update() *BackendUpdateOne {
	return NewBackendClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Backend entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Backend) Unwrap() *Backend {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Backend is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Backend) String() string {
	var builder strings.Builder
	builder.WriteString("Backend(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("create_time=")
	builder.WriteString(b.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(b.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(b.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(b.Type)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(b.Config)
	builder.WriteByte(')')
	return builder.String()
}

// Backends is a parsable slice of Backend.
type Backends []*Backend
