// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/filebrowser/filebrowser/backend/storage/ent/group"
	"github.com/filebrowser/filebrowser/backend/storage/ent/groupvolume"
	"github.com/filebrowser/filebrowser/backend/storage/ent/volume"
)

// GroupVolume is the model entity for the GroupVolume schema.
type GroupVolume struct {
	config `json:"-"`
	// GroupID holds the value of the "group_id" field.
	GroupID int `json:"group_id,omitempty"`
	// VolumeID holds the value of the "volume_id" field.
	VolumeID int `json:"volume_id,omitempty"`
	// Read holds the value of the "read" field.
	Read bool `json:"read,omitempty"`
	// Write holds the value of the "write" field.
	Write bool `json:"write,omitempty"`
	// Delete holds the value of the "delete" field.
	Delete bool `json:"delete,omitempty"`
	// Share holds the value of the "share" field.
	Share bool `json:"share,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupVolumeQuery when eager-loading is set.
	Edges        GroupVolumeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupVolumeEdges holds the relations/edges for other nodes in the graph.
type GroupVolumeEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Volume holds the value of the volume edge.
	Volume *Volume `json:"volume,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupVolumeEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// VolumeOrErr returns the Volume value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupVolumeEdges) VolumeOrErr() (*Volume, error) {
	if e.Volume != nil {
		return e.Volume, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: volume.Label}
	}
	return nil, &NotLoadedError{edge: "volume"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupVolume) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupvolume.FieldRead, groupvolume.FieldWrite, groupvolume.FieldDelete, groupvolume.FieldShare:
			values[i] = new(sql.NullBool)
		case groupvolume.FieldGroupID, groupvolume.FieldVolumeID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupVolume fields.
func (gv *GroupVolume) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupvolume.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				gv.GroupID = int(value.Int64)
			}
		case groupvolume.FieldVolumeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field volume_id", values[i])
			} else if value.Valid {
				gv.VolumeID = int(value.Int64)
			}
		case groupvolume.FieldRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field read", values[i])
			} else if value.Valid {
				gv.Read = value.Bool
			}
		case groupvolume.FieldWrite:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field write", values[i])
			} else if value.Valid {
				gv.Write = value.Bool
			}
		case groupvolume.FieldDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field delete", values[i])
			} else if value.Valid {
				gv.Delete = value.Bool
			}
		case groupvolume.FieldShare:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field share", values[i])
			} else if value.Valid {
				gv.Share = value.Bool
			}
		default:
			gv.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupVolume.
// This includes values selected through modifiers, order, etc.
func (gv *GroupVolume) Value(name string) (ent.Value, error) {
	return gv.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupVolume entity.
func (gv *GroupVolume) QueryGroup() *GroupQuery {
	return NewGroupVolumeClient(gv.config).QueryGroup(gv)
}

// QueryVolume queries the "volume" edge of the GroupVolume entity.
func (gv *GroupVolume) QueryVolume() *VolumeQuery {
	return NewGroupVolumeClient(gv.config).QueryVolume(gv)
}

// Update returns a builder for updating this GroupVolume.
// Note that you need to call GroupVolume.Unwrap() before calling this method if this GroupVolume
// was returned from a transaction, and the transaction was committed or rolled back.
func (gv *GroupVolume) Update() *GroupVolumeUpdateOne {
	return NewGroupVolumeClient(gv.config).UpdateOne(gv)
}

// Unwrap unwraps the GroupVolume entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gv *GroupVolume) Unwrap() *GroupVolume {
	_tx, ok := gv.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupVolume is not a transactional entity")
	}
	gv.config.driver = _tx.drv
	return gv
}

// String implements the fmt.Stringer.
func (gv *GroupVolume) String() string {
	var builder strings.Builder
	builder.WriteString("GroupVolume(")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", gv.GroupID))
	builder.WriteString(", ")
	builder.WriteString("volume_id=")
	builder.WriteString(fmt.Sprintf("%v", gv.VolumeID))
	builder.WriteString(", ")
	builder.WriteString("read=")
	builder.WriteString(fmt.Sprintf("%v", gv.Read))
	builder.WriteString(", ")
	builder.WriteString("write=")
	builder.WriteString(fmt.Sprintf("%v", gv.Write))
	builder.WriteString(", ")
	builder.WriteString("delete=")
	builder.WriteString(fmt.Sprintf("%v", gv.Delete))
	builder.WriteString(", ")
	builder.WriteString("share=")
	builder.WriteString(fmt.Sprintf("%v", gv.Share))
	builder.WriteByte(')')
	return builder.String()
}

// GroupVolumes is a parsable slice of GroupVolume.
type GroupVolumes []*GroupVolume
