// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/filebrowser/filebrowser/backend/storage/ent/group"
	"github.com/filebrowser/filebrowser/backend/storage/ent/groupvolume"
	"github.com/filebrowser/filebrowser/backend/storage/ent/predicate"
	"github.com/filebrowser/filebrowser/backend/storage/ent/volume"
)

// GroupVolumeQuery is the builder for querying GroupVolume entities.
type GroupVolumeQuery struct {
	config
	ctx        *QueryContext
	order      []groupvolume.OrderOption
	inters     []Interceptor
	predicates []predicate.GroupVolume
	withGroup  *GroupQuery
	withVolume *VolumeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupVolumeQuery builder.
func (gvq *GroupVolumeQuery) Where(ps ...predicate.GroupVolume) *GroupVolumeQuery {
	gvq.predicates = append(gvq.predicates, ps...)
	return gvq
}

// Limit the number of records to be returned by this query.
func (gvq *GroupVolumeQuery) Limit(limit int) *GroupVolumeQuery {
	gvq.ctx.Limit = &limit
	return gvq
}

// Offset to start from.
func (gvq *GroupVolumeQuery) Offset(offset int) *GroupVolumeQuery {
	gvq.ctx.Offset = &offset
	return gvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gvq *GroupVolumeQuery) Unique(unique bool) *GroupVolumeQuery {
	gvq.ctx.Unique = &unique
	return gvq
}

// Order specifies how the records should be ordered.
func (gvq *GroupVolumeQuery) Order(o ...groupvolume.OrderOption) *GroupVolumeQuery {
	gvq.order = append(gvq.order, o...)
	return gvq
}

// QueryGroup chains the current query on the "group" edge.
func (gvq *GroupVolumeQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: gvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupvolume.Table, groupvolume.GroupColumn, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupvolume.GroupTable, groupvolume.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(gvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVolume chains the current query on the "volume" edge.
func (gvq *GroupVolumeQuery) QueryVolume() *VolumeQuery {
	query := (&VolumeClient{config: gvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupvolume.Table, groupvolume.VolumeColumn, selector),
			sqlgraph.To(volume.Table, volume.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupvolume.VolumeTable, groupvolume.VolumeColumn),
		)
		fromU = sqlgraph.SetNeighbors(gvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupVolume entity from the query.
// Returns a *NotFoundError when no GroupVolume was found.
func (gvq *GroupVolumeQuery) First(ctx context.Context) (*GroupVolume, error) {
	nodes, err := gvq.Limit(1).All(setContextOp(ctx, gvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupvolume.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gvq *GroupVolumeQuery) FirstX(ctx context.Context) *GroupVolume {
	node, err := gvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single GroupVolume entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupVolume entity is found.
// Returns a *NotFoundError when no GroupVolume entities are found.
func (gvq *GroupVolumeQuery) Only(ctx context.Context) (*GroupVolume, error) {
	nodes, err := gvq.Limit(2).All(setContextOp(ctx, gvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupvolume.Label}
	default:
		return nil, &NotSingularError{groupvolume.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gvq *GroupVolumeQuery) OnlyX(ctx context.Context) *GroupVolume {
	node, err := gvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of GroupVolumes.
func (gvq *GroupVolumeQuery) All(ctx context.Context) ([]*GroupVolume, error) {
	ctx = setContextOp(ctx, gvq.ctx, ent.OpQueryAll)
	if err := gvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GroupVolume, *GroupVolumeQuery]()
	return withInterceptors[[]*GroupVolume](ctx, gvq, qr, gvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gvq *GroupVolumeQuery) AllX(ctx context.Context) []*GroupVolume {
	nodes, err := gvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (gvq *GroupVolumeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gvq.ctx, ent.OpQueryCount)
	if err := gvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gvq, querierCount[*GroupVolumeQuery](), gvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gvq *GroupVolumeQuery) CountX(ctx context.Context) int {
	count, err := gvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gvq *GroupVolumeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gvq.ctx, ent.OpQueryExist)
	switch _, err := gvq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gvq *GroupVolumeQuery) ExistX(ctx context.Context) bool {
	exist, err := gvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupVolumeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gvq *GroupVolumeQuery) Clone() *GroupVolumeQuery {
	if gvq == nil {
		return nil
	}
	return &GroupVolumeQuery{
		config:     gvq.config,
		ctx:        gvq.ctx.Clone(),
		order:      append([]groupvolume.OrderOption{}, gvq.order...),
		inters:     append([]Interceptor{}, gvq.inters...),
		predicates: append([]predicate.GroupVolume{}, gvq.predicates...),
		withGroup:  gvq.withGroup.Clone(),
		withVolume: gvq.withVolume.Clone(),
		// clone intermediate query.
		sql:  gvq.sql.Clone(),
		path: gvq.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (gvq *GroupVolumeQuery) WithGroup(opts ...func(*GroupQuery)) *GroupVolumeQuery {
	query := (&GroupClient{config: gvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gvq.withGroup = query
	return gvq
}

// WithVolume tells the query-builder to eager-load the nodes that are connected to
// the "volume" edge. The optional arguments are used to configure the query builder of the edge.
func (gvq *GroupVolumeQuery) WithVolume(opts ...func(*VolumeQuery)) *GroupVolumeQuery {
	query := (&VolumeClient{config: gvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gvq.withVolume = query
	return gvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GroupID int `json:"group_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupVolume.Query().
//		GroupBy(groupvolume.FieldGroupID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gvq *GroupVolumeQuery) GroupBy(field string, fields ...string) *GroupVolumeGroupBy {
	gvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroupVolumeGroupBy{build: gvq}
	grbuild.flds = &gvq.ctx.Fields
	grbuild.label = groupvolume.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GroupID int `json:"group_id,omitempty"`
//	}
//
//	client.GroupVolume.Query().
//		Select(groupvolume.FieldGroupID).
//		Scan(ctx, &v)
func (gvq *GroupVolumeQuery) Select(fields ...string) *GroupVolumeSelect {
	gvq.ctx.Fields = append(gvq.ctx.Fields, fields...)
	sbuild := &GroupVolumeSelect{GroupVolumeQuery: gvq}
	sbuild.label = groupvolume.Label
	sbuild.flds, sbuild.scan = &gvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroupVolumeSelect configured with the given aggregations.
func (gvq *GroupVolumeQuery) Aggregate(fns ...AggregateFunc) *GroupVolumeSelect {
	return gvq.Select().Aggregate(fns...)
}

func (gvq *GroupVolumeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gvq); err != nil {
				return err
			}
		}
	}
	for _, f := range gvq.ctx.Fields {
		if !groupvolume.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gvq.path != nil {
		prev, err := gvq.path(ctx)
		if err != nil {
			return err
		}
		gvq.sql = prev
	}
	return nil
}

func (gvq *GroupVolumeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupVolume, error) {
	var (
		nodes       = []*GroupVolume{}
		_spec       = gvq.querySpec()
		loadedTypes = [2]bool{
			gvq.withGroup != nil,
			gvq.withVolume != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupVolume).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupVolume{config: gvq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gvq.withGroup; query != nil {
		if err := gvq.loadGroup(ctx, query, nodes, nil,
			func(n *GroupVolume, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := gvq.withVolume; query != nil {
		if err := gvq.loadVolume(ctx, query, nodes, nil,
			func(n *GroupVolume, e *Volume) { n.Edges.Volume = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gvq *GroupVolumeQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*GroupVolume, init func(*GroupVolume), assign func(*GroupVolume, *Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GroupVolume)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gvq *GroupVolumeQuery) loadVolume(ctx context.Context, query *VolumeQuery, nodes []*GroupVolume, init func(*GroupVolume), assign func(*GroupVolume, *Volume)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GroupVolume)
	for i := range nodes {
		fk := nodes[i].VolumeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(volume.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "volume_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gvq *GroupVolumeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gvq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, gvq.driver, _spec)
}

func (gvq *GroupVolumeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(groupvolume.Table, groupvolume.Columns, nil)
	_spec.From = gvq.sql
	if unique := gvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gvq.path != nil {
		_spec.Unique = true
	}
	if fields := gvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if gvq.withGroup != nil {
			_spec.Node.AddColumnOnce(groupvolume.FieldGroupID)
		}
		if gvq.withVolume != nil {
			_spec.Node.AddColumnOnce(groupvolume.FieldVolumeID)
		}
	}
	if ps := gvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gvq *GroupVolumeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gvq.driver.Dialect())
	t1 := builder.Table(groupvolume.Table)
	columns := gvq.ctx.Fields
	if len(columns) == 0 {
		columns = groupvolume.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gvq.sql != nil {
		selector = gvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gvq.ctx.Unique != nil && *gvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gvq.predicates {
		p(selector)
	}
	for _, p := range gvq.order {
		p(selector)
	}
	if offset := gvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroupVolumeGroupBy is the group-by builder for GroupVolume entities.
type GroupVolumeGroupBy struct {
	selector
	build *GroupVolumeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gvgb *GroupVolumeGroupBy) Aggregate(fns ...AggregateFunc) *GroupVolumeGroupBy {
	gvgb.fns = append(gvgb.fns, fns...)
	return gvgb
}

// Scan applies the selector query and scans the result into the given value.
func (gvgb *GroupVolumeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gvgb.build.ctx, ent.OpQueryGroupBy)
	if err := gvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupVolumeQuery, *GroupVolumeGroupBy](ctx, gvgb.build, gvgb, gvgb.build.inters, v)
}

func (gvgb *GroupVolumeGroupBy) sqlScan(ctx context.Context, root *GroupVolumeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gvgb.fns))
	for _, fn := range gvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gvgb.flds)+len(gvgb.fns))
		for _, f := range *gvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroupVolumeSelect is the builder for selecting fields of GroupVolume entities.
type GroupVolumeSelect struct {
	*GroupVolumeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gvs *GroupVolumeSelect) Aggregate(fns ...AggregateFunc) *GroupVolumeSelect {
	gvs.fns = append(gvs.fns, fns...)
	return gvs
}

// Scan applies the selector query and scans the result into the given value.
func (gvs *GroupVolumeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gvs.ctx, ent.OpQuerySelect)
	if err := gvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupVolumeQuery, *GroupVolumeSelect](ctx, gvs.GroupVolumeQuery, gvs, gvs.inters, v)
}

func (gvs *GroupVolumeSelect) sqlScan(ctx context.Context, root *GroupVolumeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gvs.fns))
	for _, fn := range gvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
