// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/filebrowser/filebrowser/backend/storage/ent/predicate"
	"github.com/filebrowser/filebrowser/backend/storage/ent/user"
	"github.com/filebrowser/filebrowser/backend/storage/ent/uservolume"
	"github.com/filebrowser/filebrowser/backend/storage/ent/volume"
)

// UserVolumeQuery is the builder for querying UserVolume entities.
type UserVolumeQuery struct {
	config
	ctx        *QueryContext
	order      []uservolume.OrderOption
	inters     []Interceptor
	predicates []predicate.UserVolume
	withUser   *UserQuery
	withVolume *VolumeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserVolumeQuery builder.
func (uvq *UserVolumeQuery) Where(ps ...predicate.UserVolume) *UserVolumeQuery {
	uvq.predicates = append(uvq.predicates, ps...)
	return uvq
}

// Limit the number of records to be returned by this query.
func (uvq *UserVolumeQuery) Limit(limit int) *UserVolumeQuery {
	uvq.ctx.Limit = &limit
	return uvq
}

// Offset to start from.
func (uvq *UserVolumeQuery) Offset(offset int) *UserVolumeQuery {
	uvq.ctx.Offset = &offset
	return uvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uvq *UserVolumeQuery) Unique(unique bool) *UserVolumeQuery {
	uvq.ctx.Unique = &unique
	return uvq
}

// Order specifies how the records should be ordered.
func (uvq *UserVolumeQuery) Order(o ...uservolume.OrderOption) *UserVolumeQuery {
	uvq.order = append(uvq.order, o...)
	return uvq
}

// QueryUser chains the current query on the "user" edge.
func (uvq *UserVolumeQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: uvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uservolume.Table, uservolume.UserColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, uservolume.UserTable, uservolume.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVolume chains the current query on the "volume" edge.
func (uvq *UserVolumeQuery) QueryVolume() *VolumeQuery {
	query := (&VolumeClient{config: uvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uservolume.Table, uservolume.VolumeColumn, selector),
			sqlgraph.To(volume.Table, volume.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, uservolume.VolumeTable, uservolume.VolumeColumn),
		)
		fromU = sqlgraph.SetNeighbors(uvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserVolume entity from the query.
// Returns a *NotFoundError when no UserVolume was found.
func (uvq *UserVolumeQuery) First(ctx context.Context) (*UserVolume, error) {
	nodes, err := uvq.Limit(1).All(setContextOp(ctx, uvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uservolume.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uvq *UserVolumeQuery) FirstX(ctx context.Context) *UserVolume {
	node, err := uvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single UserVolume entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserVolume entity is found.
// Returns a *NotFoundError when no UserVolume entities are found.
func (uvq *UserVolumeQuery) Only(ctx context.Context) (*UserVolume, error) {
	nodes, err := uvq.Limit(2).All(setContextOp(ctx, uvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uservolume.Label}
	default:
		return nil, &NotSingularError{uservolume.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uvq *UserVolumeQuery) OnlyX(ctx context.Context) *UserVolume {
	node, err := uvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of UserVolumes.
func (uvq *UserVolumeQuery) All(ctx context.Context) ([]*UserVolume, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryAll)
	if err := uvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserVolume, *UserVolumeQuery]()
	return withInterceptors[[]*UserVolume](ctx, uvq, qr, uvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uvq *UserVolumeQuery) AllX(ctx context.Context) []*UserVolume {
	nodes, err := uvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (uvq *UserVolumeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryCount)
	if err := uvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uvq, querierCount[*UserVolumeQuery](), uvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uvq *UserVolumeQuery) CountX(ctx context.Context) int {
	count, err := uvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uvq *UserVolumeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryExist)
	switch _, err := uvq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uvq *UserVolumeQuery) ExistX(ctx context.Context) bool {
	exist, err := uvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserVolumeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uvq *UserVolumeQuery) Clone() *UserVolumeQuery {
	if uvq == nil {
		return nil
	}
	return &UserVolumeQuery{
		config:     uvq.config,
		ctx:        uvq.ctx.Clone(),
		order:      append([]uservolume.OrderOption{}, uvq.order...),
		inters:     append([]Interceptor{}, uvq.inters...),
		predicates: append([]predicate.UserVolume{}, uvq.predicates...),
		withUser:   uvq.withUser.Clone(),
		withVolume: uvq.withVolume.Clone(),
		// clone intermediate query.
		sql:  uvq.sql.Clone(),
		path: uvq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uvq *UserVolumeQuery) WithUser(opts ...func(*UserQuery)) *UserVolumeQuery {
	query := (&UserClient{config: uvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uvq.withUser = query
	return uvq
}

// WithVolume tells the query-builder to eager-load the nodes that are connected to
// the "volume" edge. The optional arguments are used to configure the query builder of the edge.
func (uvq *UserVolumeQuery) WithVolume(opts ...func(*VolumeQuery)) *UserVolumeQuery {
	query := (&VolumeClient{config: uvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uvq.withVolume = query
	return uvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserVolume.Query().
//		GroupBy(uservolume.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uvq *UserVolumeQuery) GroupBy(field string, fields ...string) *UserVolumeGroupBy {
	uvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserVolumeGroupBy{build: uvq}
	grbuild.flds = &uvq.ctx.Fields
	grbuild.label = uservolume.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserVolume.Query().
//		Select(uservolume.FieldUserID).
//		Scan(ctx, &v)
func (uvq *UserVolumeQuery) Select(fields ...string) *UserVolumeSelect {
	uvq.ctx.Fields = append(uvq.ctx.Fields, fields...)
	sbuild := &UserVolumeSelect{UserVolumeQuery: uvq}
	sbuild.label = uservolume.Label
	sbuild.flds, sbuild.scan = &uvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserVolumeSelect configured with the given aggregations.
func (uvq *UserVolumeQuery) Aggregate(fns ...AggregateFunc) *UserVolumeSelect {
	return uvq.Select().Aggregate(fns...)
}

func (uvq *UserVolumeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uvq); err != nil {
				return err
			}
		}
	}
	for _, f := range uvq.ctx.Fields {
		if !uservolume.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uvq.path != nil {
		prev, err := uvq.path(ctx)
		if err != nil {
			return err
		}
		uvq.sql = prev
	}
	return nil
}

func (uvq *UserVolumeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserVolume, error) {
	var (
		nodes       = []*UserVolume{}
		_spec       = uvq.querySpec()
		loadedTypes = [2]bool{
			uvq.withUser != nil,
			uvq.withVolume != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserVolume).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserVolume{config: uvq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uvq.withUser; query != nil {
		if err := uvq.loadUser(ctx, query, nodes, nil,
			func(n *UserVolume, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := uvq.withVolume; query != nil {
		if err := uvq.loadVolume(ctx, query, nodes, nil,
			func(n *UserVolume, e *Volume) { n.Edges.Volume = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uvq *UserVolumeQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserVolume, init func(*UserVolume), assign func(*UserVolume, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserVolume)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (uvq *UserVolumeQuery) loadVolume(ctx context.Context, query *VolumeQuery, nodes []*UserVolume, init func(*UserVolume), assign func(*UserVolume, *Volume)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserVolume)
	for i := range nodes {
		fk := nodes[i].VolumeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(volume.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "volume_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uvq *UserVolumeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uvq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, uvq.driver, _spec)
}

func (uvq *UserVolumeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(uservolume.Table, uservolume.Columns, nil)
	_spec.From = uvq.sql
	if unique := uvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uvq.path != nil {
		_spec.Unique = true
	}
	if fields := uvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if uvq.withUser != nil {
			_spec.Node.AddColumnOnce(uservolume.FieldUserID)
		}
		if uvq.withVolume != nil {
			_spec.Node.AddColumnOnce(uservolume.FieldVolumeID)
		}
	}
	if ps := uvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uvq *UserVolumeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uvq.driver.Dialect())
	t1 := builder.Table(uservolume.Table)
	columns := uvq.ctx.Fields
	if len(columns) == 0 {
		columns = uservolume.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uvq.sql != nil {
		selector = uvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uvq.ctx.Unique != nil && *uvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uvq.predicates {
		p(selector)
	}
	for _, p := range uvq.order {
		p(selector)
	}
	if offset := uvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserVolumeGroupBy is the group-by builder for UserVolume entities.
type UserVolumeGroupBy struct {
	selector
	build *UserVolumeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uvgb *UserVolumeGroupBy) Aggregate(fns ...AggregateFunc) *UserVolumeGroupBy {
	uvgb.fns = append(uvgb.fns, fns...)
	return uvgb
}

// Scan applies the selector query and scans the result into the given value.
func (uvgb *UserVolumeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uvgb.build.ctx, ent.OpQueryGroupBy)
	if err := uvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserVolumeQuery, *UserVolumeGroupBy](ctx, uvgb.build, uvgb, uvgb.build.inters, v)
}

func (uvgb *UserVolumeGroupBy) sqlScan(ctx context.Context, root *UserVolumeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uvgb.fns))
	for _, fn := range uvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uvgb.flds)+len(uvgb.fns))
		for _, f := range *uvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserVolumeSelect is the builder for selecting fields of UserVolume entities.
type UserVolumeSelect struct {
	*UserVolumeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uvs *UserVolumeSelect) Aggregate(fns ...AggregateFunc) *UserVolumeSelect {
	uvs.fns = append(uvs.fns, fns...)
	return uvs
}

// Scan applies the selector query and scans the result into the given value.
func (uvs *UserVolumeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uvs.ctx, ent.OpQuerySelect)
	if err := uvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserVolumeQuery, *UserVolumeSelect](ctx, uvs.UserVolumeQuery, uvs, uvs.inters, v)
}

func (uvs *UserVolumeSelect) sqlScan(ctx context.Context, root *UserVolumeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uvs.fns))
	for _, fn := range uvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
