// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/filebrowser/filebrowser/backend/storage/ent/user"
	"github.com/filebrowser/filebrowser/backend/storage/ent/uservolume"
	"github.com/filebrowser/filebrowser/backend/storage/ent/volume"
)

// UserVolumeCreate is the builder for creating a UserVolume entity.
type UserVolumeCreate struct {
	config
	mutation *UserVolumeMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (uvc *UserVolumeCreate) SetUserID(i int) *UserVolumeCreate {
	uvc.mutation.SetUserID(i)
	return uvc
}

// SetVolumeID sets the "volume_id" field.
func (uvc *UserVolumeCreate) SetVolumeID(i int) *UserVolumeCreate {
	uvc.mutation.SetVolumeID(i)
	return uvc
}

// SetRead sets the "read" field.
func (uvc *UserVolumeCreate) SetRead(b bool) *UserVolumeCreate {
	uvc.mutation.SetRead(b)
	return uvc
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (uvc *UserVolumeCreate) SetNillableRead(b *bool) *UserVolumeCreate {
	if b != nil {
		uvc.SetRead(*b)
	}
	return uvc
}

// SetWrite sets the "write" field.
func (uvc *UserVolumeCreate) SetWrite(b bool) *UserVolumeCreate {
	uvc.mutation.SetWrite(b)
	return uvc
}

// SetNillableWrite sets the "write" field if the given value is not nil.
func (uvc *UserVolumeCreate) SetNillableWrite(b *bool) *UserVolumeCreate {
	if b != nil {
		uvc.SetWrite(*b)
	}
	return uvc
}

// SetDelete sets the "delete" field.
func (uvc *UserVolumeCreate) SetDelete(b bool) *UserVolumeCreate {
	uvc.mutation.SetDelete(b)
	return uvc
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (uvc *UserVolumeCreate) SetNillableDelete(b *bool) *UserVolumeCreate {
	if b != nil {
		uvc.SetDelete(*b)
	}
	return uvc
}

// SetShare sets the "share" field.
func (uvc *UserVolumeCreate) SetShare(b bool) *UserVolumeCreate {
	uvc.mutation.SetShare(b)
	return uvc
}

// SetNillableShare sets the "share" field if the given value is not nil.
func (uvc *UserVolumeCreate) SetNillableShare(b *bool) *UserVolumeCreate {
	if b != nil {
		uvc.SetShare(*b)
	}
	return uvc
}

// SetUser sets the "user" edge to the User entity.
func (uvc *UserVolumeCreate) SetUser(u *User) *UserVolumeCreate {
	return uvc.SetUserID(u.ID)
}

// SetVolume sets the "volume" edge to the Volume entity.
func (uvc *UserVolumeCreate) SetVolume(v *Volume) *UserVolumeCreate {
	return uvc.SetVolumeID(v.ID)
}

// Mutation returns the UserVolumeMutation object of the builder.
func (uvc *UserVolumeCreate) Mutation() *UserVolumeMutation {
	return uvc.mutation
}

// Save creates the UserVolume in the database.
func (uvc *UserVolumeCreate) Save(ctx context.Context) (*UserVolume, error) {
	uvc.defaults()
	return withHooks(ctx, uvc.sqlSave, uvc.mutation, uvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uvc *UserVolumeCreate) SaveX(ctx context.Context) *UserVolume {
	v, err := uvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uvc *UserVolumeCreate) Exec(ctx context.Context) error {
	_, err := uvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvc *UserVolumeCreate) ExecX(ctx context.Context) {
	if err := uvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uvc *UserVolumeCreate) defaults() {
	if _, ok := uvc.mutation.Read(); !ok {
		v := uservolume.DefaultRead
		uvc.mutation.SetRead(v)
	}
	if _, ok := uvc.mutation.Write(); !ok {
		v := uservolume.DefaultWrite
		uvc.mutation.SetWrite(v)
	}
	if _, ok := uvc.mutation.Delete(); !ok {
		v := uservolume.DefaultDelete
		uvc.mutation.SetDelete(v)
	}
	if _, ok := uvc.mutation.Share(); !ok {
		v := uservolume.DefaultShare
		uvc.mutation.SetShare(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uvc *UserVolumeCreate) check() error {
	if _, ok := uvc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserVolume.user_id"`)}
	}
	if _, ok := uvc.mutation.VolumeID(); !ok {
		return &ValidationError{Name: "volume_id", err: errors.New(`ent: missing required field "UserVolume.volume_id"`)}
	}
	if _, ok := uvc.mutation.Read(); !ok {
		return &ValidationError{Name: "read", err: errors.New(`ent: missing required field "UserVolume.read"`)}
	}
	if _, ok := uvc.mutation.Write(); !ok {
		return &ValidationError{Name: "write", err: errors.New(`ent: missing required field "UserVolume.write"`)}
	}
	if _, ok := uvc.mutation.Delete(); !ok {
		return &ValidationError{Name: "delete", err: errors.New(`ent: missing required field "UserVolume.delete"`)}
	}
	if _, ok := uvc.mutation.Share(); !ok {
		return &ValidationError{Name: "share", err: errors.New(`ent: missing required field "UserVolume.share"`)}
	}
	if len(uvc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserVolume.user"`)}
	}
	if len(uvc.mutation.VolumeIDs()) == 0 {
		return &ValidationError{Name: "volume", err: errors.New(`ent: missing required edge "UserVolume.volume"`)}
	}
	return nil
}

func (uvc *UserVolumeCreate) sqlSave(ctx context.Context) (*UserVolume, error) {
	if err := uvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (uvc *UserVolumeCreate) createSpec() (*UserVolume, *sqlgraph.CreateSpec) {
	var (
		_node = &UserVolume{config: uvc.config}
		_spec = sqlgraph.NewCreateSpec(uservolume.Table, nil)
	)
	if value, ok := uvc.mutation.Read(); ok {
		_spec.SetField(uservolume.FieldRead, field.TypeBool, value)
		_node.Read = value
	}
	if value, ok := uvc.mutation.Write(); ok {
		_spec.SetField(uservolume.FieldWrite, field.TypeBool, value)
		_node.Write = value
	}
	if value, ok := uvc.mutation.Delete(); ok {
		_spec.SetField(uservolume.FieldDelete, field.TypeBool, value)
		_node.Delete = value
	}
	if value, ok := uvc.mutation.Share(); ok {
		_spec.SetField(uservolume.FieldShare, field.TypeBool, value)
		_node.Share = value
	}
	if nodes := uvc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservolume.UserTable,
			Columns: []string{uservolume.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uvc.mutation.VolumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservolume.VolumeTable,
			Columns: []string{uservolume.VolumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(volume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VolumeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserVolumeCreateBulk is the builder for creating many UserVolume entities in bulk.
type UserVolumeCreateBulk struct {
	config
	err      error
	builders []*UserVolumeCreate
}

// Save creates the UserVolume entities in the database.
func (uvcb *UserVolumeCreateBulk) Save(ctx context.Context) ([]*UserVolume, error) {
	if uvcb.err != nil {
		return nil, uvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uvcb.builders))
	nodes := make([]*UserVolume, len(uvcb.builders))
	mutators := make([]Mutator, len(uvcb.builders))
	for i := range uvcb.builders {
		func(i int, root context.Context) {
			builder := uvcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserVolumeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uvcb *UserVolumeCreateBulk) SaveX(ctx context.Context) []*UserVolume {
	v, err := uvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uvcb *UserVolumeCreateBulk) Exec(ctx context.Context) error {
	_, err := uvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvcb *UserVolumeCreateBulk) ExecX(ctx context.Context) {
	if err := uvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
