// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/filebrowser/filebrowser/backend/storage/ent/backend"
	"github.com/filebrowser/filebrowser/backend/storage/ent/group"
	"github.com/filebrowser/filebrowser/backend/storage/ent/predicate"
	"github.com/filebrowser/filebrowser/backend/storage/ent/user"
	"github.com/filebrowser/filebrowser/backend/storage/ent/volume"
)

// VolumeUpdate is the builder for updating Volume entities.
type VolumeUpdate struct {
	config
	hooks    []Hook
	mutation *VolumeMutation
}

// Where appends a list predicates to the VolumeUpdate builder.
func (vu *VolumeUpdate) Where(ps ...predicate.Volume) *VolumeUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetUpdateTime sets the "update_time" field.
func (vu *VolumeUpdate) SetUpdateTime(t time.Time) *VolumeUpdate {
	vu.mutation.SetUpdateTime(t)
	return vu
}

// SetName sets the "name" field.
func (vu *VolumeUpdate) SetName(s string) *VolumeUpdate {
	vu.mutation.SetName(s)
	return vu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (vu *VolumeUpdate) SetNillableName(s *string) *VolumeUpdate {
	if s != nil {
		vu.SetName(*s)
	}
	return vu
}

// SetPath sets the "path" field.
func (vu *VolumeUpdate) SetPath(s string) *VolumeUpdate {
	vu.mutation.SetPath(s)
	return vu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (vu *VolumeUpdate) SetNillablePath(s *string) *VolumeUpdate {
	if s != nil {
		vu.SetPath(*s)
	}
	return vu
}

// SetBackendID sets the "backend_id" field.
func (vu *VolumeUpdate) SetBackendID(i int) *VolumeUpdate {
	vu.mutation.SetBackendID(i)
	return vu
}

// SetNillableBackendID sets the "backend_id" field if the given value is not nil.
func (vu *VolumeUpdate) SetNillableBackendID(i *int) *VolumeUpdate {
	if i != nil {
		vu.SetBackendID(*i)
	}
	return vu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (vu *VolumeUpdate) AddUserIDs(ids ...int) *VolumeUpdate {
	vu.mutation.AddUserIDs(ids...)
	return vu
}

// AddUsers adds the "users" edges to the User entity.
func (vu *VolumeUpdate) AddUsers(u ...*User) *VolumeUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vu.AddUserIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (vu *VolumeUpdate) AddGroupIDs(ids ...int) *VolumeUpdate {
	vu.mutation.AddGroupIDs(ids...)
	return vu
}

// AddGroups adds the "groups" edges to the Group entity.
func (vu *VolumeUpdate) AddGroups(g ...*Group) *VolumeUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return vu.AddGroupIDs(ids...)
}

// SetBackend sets the "backend" edge to the Backend entity.
func (vu *VolumeUpdate) SetBackend(b *Backend) *VolumeUpdate {
	return vu.SetBackendID(b.ID)
}

// Mutation returns the VolumeMutation object of the builder.
func (vu *VolumeUpdate) Mutation() *VolumeMutation {
	return vu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (vu *VolumeUpdate) ClearUsers() *VolumeUpdate {
	vu.mutation.ClearUsers()
	return vu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (vu *VolumeUpdate) RemoveUserIDs(ids ...int) *VolumeUpdate {
	vu.mutation.RemoveUserIDs(ids...)
	return vu
}

// RemoveUsers removes "users" edges to User entities.
func (vu *VolumeUpdate) RemoveUsers(u ...*User) *VolumeUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vu.RemoveUserIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (vu *VolumeUpdate) ClearGroups() *VolumeUpdate {
	vu.mutation.ClearGroups()
	return vu
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (vu *VolumeUpdate) RemoveGroupIDs(ids ...int) *VolumeUpdate {
	vu.mutation.RemoveGroupIDs(ids...)
	return vu
}

// RemoveGroups removes "groups" edges to Group entities.
func (vu *VolumeUpdate) RemoveGroups(g ...*Group) *VolumeUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return vu.RemoveGroupIDs(ids...)
}

// ClearBackend clears the "backend" edge to the Backend entity.
func (vu *VolumeUpdate) ClearBackend() *VolumeUpdate {
	vu.mutation.ClearBackend()
	return vu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *VolumeUpdate) Save(ctx context.Context) (int, error) {
	vu.defaults()
	return withHooks(ctx, vu.sqlSave, vu.mutation, vu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vu *VolumeUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *VolumeUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *VolumeUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vu *VolumeUpdate) defaults() {
	if _, ok := vu.mutation.UpdateTime(); !ok {
		v := volume.UpdateDefaultUpdateTime()
		vu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vu *VolumeUpdate) check() error {
	if v, ok := vu.mutation.Name(); ok {
		if err := volume.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Volume.name": %w`, err)}
		}
	}
	if v, ok := vu.mutation.Path(); ok {
		if err := volume.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Volume.path": %w`, err)}
		}
	}
	if vu.mutation.BackendCleared() && len(vu.mutation.BackendIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Volume.backend"`)
	}
	return nil
}

func (vu *VolumeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := vu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(volume.Table, volume.Columns, sqlgraph.NewFieldSpec(volume.FieldID, field.TypeInt))
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.UpdateTime(); ok {
		_spec.SetField(volume.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := vu.mutation.Name(); ok {
		_spec.SetField(volume.FieldName, field.TypeString, value)
	}
	if value, ok := vu.mutation.Path(); ok {
		_spec.SetField(volume.FieldPath, field.TypeString, value)
	}
	if vu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.UsersTable,
			Columns: volume.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		createE := &UserVolumeCreate{config: vu.config, mutation: newUserVolumeMutation(vu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !vu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.UsersTable,
			Columns: volume.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserVolumeCreate{config: vu.config, mutation: newUserVolumeMutation(vu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.UsersTable,
			Columns: volume.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserVolumeCreate{config: vu.config, mutation: newUserVolumeMutation(vu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vu.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.GroupsTable,
			Columns: volume.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		createE := &GroupVolumeCreate{config: vu.config, mutation: newGroupVolumeMutation(vu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !vu.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.GroupsTable,
			Columns: volume.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &GroupVolumeCreate{config: vu.config, mutation: newGroupVolumeMutation(vu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.GroupsTable,
			Columns: volume.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &GroupVolumeCreate{config: vu.config, mutation: newGroupVolumeMutation(vu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vu.mutation.BackendCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   volume.BackendTable,
			Columns: []string{volume.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.BackendIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   volume.BackendTable,
			Columns: []string{volume.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{volume.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vu.mutation.done = true
	return n, nil
}

// VolumeUpdateOne is the builder for updating a single Volume entity.
type VolumeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VolumeMutation
}

// SetUpdateTime sets the "update_time" field.
func (vuo *VolumeUpdateOne) SetUpdateTime(t time.Time) *VolumeUpdateOne {
	vuo.mutation.SetUpdateTime(t)
	return vuo
}

// SetName sets the "name" field.
func (vuo *VolumeUpdateOne) SetName(s string) *VolumeUpdateOne {
	vuo.mutation.SetName(s)
	return vuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (vuo *VolumeUpdateOne) SetNillableName(s *string) *VolumeUpdateOne {
	if s != nil {
		vuo.SetName(*s)
	}
	return vuo
}

// SetPath sets the "path" field.
func (vuo *VolumeUpdateOne) SetPath(s string) *VolumeUpdateOne {
	vuo.mutation.SetPath(s)
	return vuo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (vuo *VolumeUpdateOne) SetNillablePath(s *string) *VolumeUpdateOne {
	if s != nil {
		vuo.SetPath(*s)
	}
	return vuo
}

// SetBackendID sets the "backend_id" field.
func (vuo *VolumeUpdateOne) SetBackendID(i int) *VolumeUpdateOne {
	vuo.mutation.SetBackendID(i)
	return vuo
}

// SetNillableBackendID sets the "backend_id" field if the given value is not nil.
func (vuo *VolumeUpdateOne) SetNillableBackendID(i *int) *VolumeUpdateOne {
	if i != nil {
		vuo.SetBackendID(*i)
	}
	return vuo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (vuo *VolumeUpdateOne) AddUserIDs(ids ...int) *VolumeUpdateOne {
	vuo.mutation.AddUserIDs(ids...)
	return vuo
}

// AddUsers adds the "users" edges to the User entity.
func (vuo *VolumeUpdateOne) AddUsers(u ...*User) *VolumeUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vuo.AddUserIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (vuo *VolumeUpdateOne) AddGroupIDs(ids ...int) *VolumeUpdateOne {
	vuo.mutation.AddGroupIDs(ids...)
	return vuo
}

// AddGroups adds the "groups" edges to the Group entity.
func (vuo *VolumeUpdateOne) AddGroups(g ...*Group) *VolumeUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return vuo.AddGroupIDs(ids...)
}

// SetBackend sets the "backend" edge to the Backend entity.
func (vuo *VolumeUpdateOne) SetBackend(b *Backend) *VolumeUpdateOne {
	return vuo.SetBackendID(b.ID)
}

// Mutation returns the VolumeMutation object of the builder.
func (vuo *VolumeUpdateOne) Mutation() *VolumeMutation {
	return vuo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (vuo *VolumeUpdateOne) ClearUsers() *VolumeUpdateOne {
	vuo.mutation.ClearUsers()
	return vuo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (vuo *VolumeUpdateOne) RemoveUserIDs(ids ...int) *VolumeUpdateOne {
	vuo.mutation.RemoveUserIDs(ids...)
	return vuo
}

// RemoveUsers removes "users" edges to User entities.
func (vuo *VolumeUpdateOne) RemoveUsers(u ...*User) *VolumeUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vuo.RemoveUserIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (vuo *VolumeUpdateOne) ClearGroups() *VolumeUpdateOne {
	vuo.mutation.ClearGroups()
	return vuo
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (vuo *VolumeUpdateOne) RemoveGroupIDs(ids ...int) *VolumeUpdateOne {
	vuo.mutation.RemoveGroupIDs(ids...)
	return vuo
}

// RemoveGroups removes "groups" edges to Group entities.
func (vuo *VolumeUpdateOne) RemoveGroups(g ...*Group) *VolumeUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return vuo.RemoveGroupIDs(ids...)
}

// ClearBackend clears the "backend" edge to the Backend entity.
func (vuo *VolumeUpdateOne) ClearBackend() *VolumeUpdateOne {
	vuo.mutation.ClearBackend()
	return vuo
}

// Where appends a list predicates to the VolumeUpdate builder.
func (vuo *VolumeUpdateOne) Where(ps ...predicate.Volume) *VolumeUpdateOne {
	vuo.mutation.Where(ps...)
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *VolumeUpdateOne) Select(field string, fields ...string) *VolumeUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated Volume entity.
func (vuo *VolumeUpdateOne) Save(ctx context.Context) (*Volume, error) {
	vuo.defaults()
	return withHooks(ctx, vuo.sqlSave, vuo.mutation, vuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *VolumeUpdateOne) SaveX(ctx context.Context) *Volume {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *VolumeUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *VolumeUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vuo *VolumeUpdateOne) defaults() {
	if _, ok := vuo.mutation.UpdateTime(); !ok {
		v := volume.UpdateDefaultUpdateTime()
		vuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vuo *VolumeUpdateOne) check() error {
	if v, ok := vuo.mutation.Name(); ok {
		if err := volume.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Volume.name": %w`, err)}
		}
	}
	if v, ok := vuo.mutation.Path(); ok {
		if err := volume.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Volume.path": %w`, err)}
		}
	}
	if vuo.mutation.BackendCleared() && len(vuo.mutation.BackendIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Volume.backend"`)
	}
	return nil
}

func (vuo *VolumeUpdateOne) sqlSave(ctx context.Context) (_node *Volume, err error) {
	if err := vuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(volume.Table, volume.Columns, sqlgraph.NewFieldSpec(volume.FieldID, field.TypeInt))
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Volume.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, volume.FieldID)
		for _, f := range fields {
			if !volume.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != volume.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vuo.mutation.UpdateTime(); ok {
		_spec.SetField(volume.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := vuo.mutation.Name(); ok {
		_spec.SetField(volume.FieldName, field.TypeString, value)
	}
	if value, ok := vuo.mutation.Path(); ok {
		_spec.SetField(volume.FieldPath, field.TypeString, value)
	}
	if vuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.UsersTable,
			Columns: volume.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		createE := &UserVolumeCreate{config: vuo.config, mutation: newUserVolumeMutation(vuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !vuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.UsersTable,
			Columns: volume.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserVolumeCreate{config: vuo.config, mutation: newUserVolumeMutation(vuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.UsersTable,
			Columns: volume.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserVolumeCreate{config: vuo.config, mutation: newUserVolumeMutation(vuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vuo.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.GroupsTable,
			Columns: volume.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		createE := &GroupVolumeCreate{config: vuo.config, mutation: newGroupVolumeMutation(vuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !vuo.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.GroupsTable,
			Columns: volume.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &GroupVolumeCreate{config: vuo.config, mutation: newGroupVolumeMutation(vuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   volume.GroupsTable,
			Columns: volume.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &GroupVolumeCreate{config: vuo.config, mutation: newGroupVolumeMutation(vuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vuo.mutation.BackendCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   volume.BackendTable,
			Columns: []string{volume.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.BackendIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   volume.BackendTable,
			Columns: []string{volume.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Volume{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{volume.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vuo.mutation.done = true
	return _node, nil
}
