// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/filebrowser/filebrowser/backend/storage/ent/backend"
	"github.com/filebrowser/filebrowser/backend/storage/ent/group"
	"github.com/filebrowser/filebrowser/backend/storage/ent/groupvolume"
	"github.com/filebrowser/filebrowser/backend/storage/ent/predicate"
	"github.com/filebrowser/filebrowser/backend/storage/ent/user"
	"github.com/filebrowser/filebrowser/backend/storage/ent/uservolume"
	"github.com/filebrowser/filebrowser/backend/storage/ent/volume"
)

// VolumeQuery is the builder for querying Volume entities.
type VolumeQuery struct {
	config
	ctx             *QueryContext
	order           []volume.OrderOption
	inters          []Interceptor
	predicates      []predicate.Volume
	withUsers       *UserQuery
	withGroups      *GroupQuery
	withBackend     *BackendQuery
	withUserVolume  *UserVolumeQuery
	withGroupVolume *GroupVolumeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VolumeQuery builder.
func (vq *VolumeQuery) Where(ps ...predicate.Volume) *VolumeQuery {
	vq.predicates = append(vq.predicates, ps...)
	return vq
}

// Limit the number of records to be returned by this query.
func (vq *VolumeQuery) Limit(limit int) *VolumeQuery {
	vq.ctx.Limit = &limit
	return vq
}

// Offset to start from.
func (vq *VolumeQuery) Offset(offset int) *VolumeQuery {
	vq.ctx.Offset = &offset
	return vq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vq *VolumeQuery) Unique(unique bool) *VolumeQuery {
	vq.ctx.Unique = &unique
	return vq
}

// Order specifies how the records should be ordered.
func (vq *VolumeQuery) Order(o ...volume.OrderOption) *VolumeQuery {
	vq.order = append(vq.order, o...)
	return vq
}

// QueryUsers chains the current query on the "users" edge.
func (vq *VolumeQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(volume.Table, volume.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, volume.UsersTable, volume.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (vq *VolumeQuery) QueryGroups() *GroupQuery {
	query := (&GroupClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(volume.Table, volume.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, volume.GroupsTable, volume.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBackend chains the current query on the "backend" edge.
func (vq *VolumeQuery) QueryBackend() *BackendQuery {
	query := (&BackendClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(volume.Table, volume.FieldID, selector),
			sqlgraph.To(backend.Table, backend.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, volume.BackendTable, volume.BackendColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUserVolume chains the current query on the "user_volume" edge.
func (vq *VolumeQuery) QueryUserVolume() *UserVolumeQuery {
	query := (&UserVolumeClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(volume.Table, volume.FieldID, selector),
			sqlgraph.To(uservolume.Table, uservolume.VolumeColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, volume.UserVolumeTable, volume.UserVolumeColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroupVolume chains the current query on the "group_volume" edge.
func (vq *VolumeQuery) QueryGroupVolume() *GroupVolumeQuery {
	query := (&GroupVolumeClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(volume.Table, volume.FieldID, selector),
			sqlgraph.To(groupvolume.Table, groupvolume.VolumeColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, volume.GroupVolumeTable, volume.GroupVolumeColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Volume entity from the query.
// Returns a *NotFoundError when no Volume was found.
func (vq *VolumeQuery) First(ctx context.Context) (*Volume, error) {
	nodes, err := vq.Limit(1).All(setContextOp(ctx, vq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{volume.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vq *VolumeQuery) FirstX(ctx context.Context) *Volume {
	node, err := vq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Volume ID from the query.
// Returns a *NotFoundError when no Volume ID was found.
func (vq *VolumeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(1).IDs(setContextOp(ctx, vq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{volume.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vq *VolumeQuery) FirstIDX(ctx context.Context) int {
	id, err := vq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Volume entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Volume entity is found.
// Returns a *NotFoundError when no Volume entities are found.
func (vq *VolumeQuery) Only(ctx context.Context) (*Volume, error) {
	nodes, err := vq.Limit(2).All(setContextOp(ctx, vq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{volume.Label}
	default:
		return nil, &NotSingularError{volume.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vq *VolumeQuery) OnlyX(ctx context.Context) *Volume {
	node, err := vq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Volume ID in the query.
// Returns a *NotSingularError when more than one Volume ID is found.
// Returns a *NotFoundError when no entities are found.
func (vq *VolumeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(2).IDs(setContextOp(ctx, vq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{volume.Label}
	default:
		err = &NotSingularError{volume.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vq *VolumeQuery) OnlyIDX(ctx context.Context) int {
	id, err := vq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Volumes.
func (vq *VolumeQuery) All(ctx context.Context) ([]*Volume, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryAll)
	if err := vq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Volume, *VolumeQuery]()
	return withInterceptors[[]*Volume](ctx, vq, qr, vq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vq *VolumeQuery) AllX(ctx context.Context) []*Volume {
	nodes, err := vq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Volume IDs.
func (vq *VolumeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vq.ctx.Unique == nil && vq.path != nil {
		vq.Unique(true)
	}
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryIDs)
	if err = vq.Select(volume.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vq *VolumeQuery) IDsX(ctx context.Context) []int {
	ids, err := vq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vq *VolumeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryCount)
	if err := vq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vq, querierCount[*VolumeQuery](), vq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vq *VolumeQuery) CountX(ctx context.Context) int {
	count, err := vq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vq *VolumeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryExist)
	switch _, err := vq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vq *VolumeQuery) ExistX(ctx context.Context) bool {
	exist, err := vq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VolumeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vq *VolumeQuery) Clone() *VolumeQuery {
	if vq == nil {
		return nil
	}
	return &VolumeQuery{
		config:          vq.config,
		ctx:             vq.ctx.Clone(),
		order:           append([]volume.OrderOption{}, vq.order...),
		inters:          append([]Interceptor{}, vq.inters...),
		predicates:      append([]predicate.Volume{}, vq.predicates...),
		withUsers:       vq.withUsers.Clone(),
		withGroups:      vq.withGroups.Clone(),
		withBackend:     vq.withBackend.Clone(),
		withUserVolume:  vq.withUserVolume.Clone(),
		withGroupVolume: vq.withGroupVolume.Clone(),
		// clone intermediate query.
		sql:  vq.sql.Clone(),
		path: vq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VolumeQuery) WithUsers(opts ...func(*UserQuery)) *VolumeQuery {
	query := (&UserClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withUsers = query
	return vq
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VolumeQuery) WithGroups(opts ...func(*GroupQuery)) *VolumeQuery {
	query := (&GroupClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withGroups = query
	return vq
}

// WithBackend tells the query-builder to eager-load the nodes that are connected to
// the "backend" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VolumeQuery) WithBackend(opts ...func(*BackendQuery)) *VolumeQuery {
	query := (&BackendClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withBackend = query
	return vq
}

// WithUserVolume tells the query-builder to eager-load the nodes that are connected to
// the "user_volume" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VolumeQuery) WithUserVolume(opts ...func(*UserVolumeQuery)) *VolumeQuery {
	query := (&UserVolumeClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withUserVolume = query
	return vq
}

// WithGroupVolume tells the query-builder to eager-load the nodes that are connected to
// the "group_volume" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VolumeQuery) WithGroupVolume(opts ...func(*GroupVolumeQuery)) *VolumeQuery {
	query := (&GroupVolumeClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withGroupVolume = query
	return vq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Volume.Query().
//		GroupBy(volume.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vq *VolumeQuery) GroupBy(field string, fields ...string) *VolumeGroupBy {
	vq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VolumeGroupBy{build: vq}
	grbuild.flds = &vq.ctx.Fields
	grbuild.label = volume.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Volume.Query().
//		Select(volume.FieldCreateTime).
//		Scan(ctx, &v)
func (vq *VolumeQuery) Select(fields ...string) *VolumeSelect {
	vq.ctx.Fields = append(vq.ctx.Fields, fields...)
	sbuild := &VolumeSelect{VolumeQuery: vq}
	sbuild.label = volume.Label
	sbuild.flds, sbuild.scan = &vq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VolumeSelect configured with the given aggregations.
func (vq *VolumeQuery) Aggregate(fns ...AggregateFunc) *VolumeSelect {
	return vq.Select().Aggregate(fns...)
}

func (vq *VolumeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vq); err != nil {
				return err
			}
		}
	}
	for _, f := range vq.ctx.Fields {
		if !volume.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vq.path != nil {
		prev, err := vq.path(ctx)
		if err != nil {
			return err
		}
		vq.sql = prev
	}
	return nil
}

func (vq *VolumeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Volume, error) {
	var (
		nodes       = []*Volume{}
		_spec       = vq.querySpec()
		loadedTypes = [5]bool{
			vq.withUsers != nil,
			vq.withGroups != nil,
			vq.withBackend != nil,
			vq.withUserVolume != nil,
			vq.withGroupVolume != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Volume).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Volume{config: vq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vq.withUsers; query != nil {
		if err := vq.loadUsers(ctx, query, nodes,
			func(n *Volume) { n.Edges.Users = []*User{} },
			func(n *Volume, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withGroups; query != nil {
		if err := vq.loadGroups(ctx, query, nodes,
			func(n *Volume) { n.Edges.Groups = []*Group{} },
			func(n *Volume, e *Group) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withBackend; query != nil {
		if err := vq.loadBackend(ctx, query, nodes, nil,
			func(n *Volume, e *Backend) { n.Edges.Backend = e }); err != nil {
			return nil, err
		}
	}
	if query := vq.withUserVolume; query != nil {
		if err := vq.loadUserVolume(ctx, query, nodes,
			func(n *Volume) { n.Edges.UserVolume = []*UserVolume{} },
			func(n *Volume, e *UserVolume) { n.Edges.UserVolume = append(n.Edges.UserVolume, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withGroupVolume; query != nil {
		if err := vq.loadGroupVolume(ctx, query, nodes,
			func(n *Volume) { n.Edges.GroupVolume = []*GroupVolume{} },
			func(n *Volume, e *GroupVolume) { n.Edges.GroupVolume = append(n.Edges.GroupVolume, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vq *VolumeQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*Volume, init func(*Volume), assign func(*Volume, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Volume)
	nids := make(map[int]map[*Volume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(volume.UsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(volume.UsersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(volume.UsersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(volume.UsersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Volume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (vq *VolumeQuery) loadGroups(ctx context.Context, query *GroupQuery, nodes []*Volume, init func(*Volume), assign func(*Volume, *Group)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Volume)
	nids := make(map[int]map[*Volume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(volume.GroupsTable)
		s.Join(joinT).On(s.C(group.FieldID), joinT.C(volume.GroupsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(volume.GroupsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(volume.GroupsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Volume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Group](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (vq *VolumeQuery) loadBackend(ctx context.Context, query *BackendQuery, nodes []*Volume, init func(*Volume), assign func(*Volume, *Backend)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Volume)
	for i := range nodes {
		fk := nodes[i].BackendID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(backend.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "backend_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (vq *VolumeQuery) loadUserVolume(ctx context.Context, query *UserVolumeQuery, nodes []*Volume, init func(*Volume), assign func(*Volume, *UserVolume)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Volume)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(uservolume.FieldVolumeID)
	}
	query.Where(predicate.UserVolume(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(volume.UserVolumeColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VolumeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "volume_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}
func (vq *VolumeQuery) loadGroupVolume(ctx context.Context, query *GroupVolumeQuery, nodes []*Volume, init func(*Volume), assign func(*Volume, *GroupVolume)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Volume)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(groupvolume.FieldVolumeID)
	}
	query.Where(predicate.GroupVolume(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(volume.GroupVolumeColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VolumeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "volume_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (vq *VolumeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vq.querySpec()
	_spec.Node.Columns = vq.ctx.Fields
	if len(vq.ctx.Fields) > 0 {
		_spec.Unique = vq.ctx.Unique != nil && *vq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vq.driver, _spec)
}

func (vq *VolumeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(volume.Table, volume.Columns, sqlgraph.NewFieldSpec(volume.FieldID, field.TypeInt))
	_spec.From = vq.sql
	if unique := vq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vq.path != nil {
		_spec.Unique = true
	}
	if fields := vq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, volume.FieldID)
		for i := range fields {
			if fields[i] != volume.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if vq.withBackend != nil {
			_spec.Node.AddColumnOnce(volume.FieldBackendID)
		}
	}
	if ps := vq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vq *VolumeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vq.driver.Dialect())
	t1 := builder.Table(volume.Table)
	columns := vq.ctx.Fields
	if len(columns) == 0 {
		columns = volume.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vq.sql != nil {
		selector = vq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vq.ctx.Unique != nil && *vq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vq.predicates {
		p(selector)
	}
	for _, p := range vq.order {
		p(selector)
	}
	if offset := vq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VolumeGroupBy is the group-by builder for Volume entities.
type VolumeGroupBy struct {
	selector
	build *VolumeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vgb *VolumeGroupBy) Aggregate(fns ...AggregateFunc) *VolumeGroupBy {
	vgb.fns = append(vgb.fns, fns...)
	return vgb
}

// Scan applies the selector query and scans the result into the given value.
func (vgb *VolumeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vgb.build.ctx, ent.OpQueryGroupBy)
	if err := vgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VolumeQuery, *VolumeGroupBy](ctx, vgb.build, vgb, vgb.build.inters, v)
}

func (vgb *VolumeGroupBy) sqlScan(ctx context.Context, root *VolumeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vgb.fns))
	for _, fn := range vgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vgb.flds)+len(vgb.fns))
		for _, f := range *vgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VolumeSelect is the builder for selecting fields of Volume entities.
type VolumeSelect struct {
	*VolumeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vs *VolumeSelect) Aggregate(fns ...AggregateFunc) *VolumeSelect {
	vs.fns = append(vs.fns, fns...)
	return vs
}

// Scan applies the selector query and scans the result into the given value.
func (vs *VolumeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vs.ctx, ent.OpQuerySelect)
	if err := vs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VolumeQuery, *VolumeSelect](ctx, vs.VolumeQuery, vs, vs.inters, v)
}

func (vs *VolumeSelect) sqlScan(ctx context.Context, root *VolumeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vs.fns))
	for _, fn := range vs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
