// Code generated by go-enum
// DO NOT EDIT!

package domain

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// ResourceUser is a Resource of type User.
	ResourceUser Resource = iota
	// ResourceFile is a Resource of type File.
	ResourceFile
)

const _ResourceName = "userfile"

var _ResourceNames = []string{
	_ResourceName[0:4],
	_ResourceName[4:8],
}

// ResourceNames returns a list of possible string values of Resource.
func ResourceNames() []string {
	tmp := make([]string, len(_ResourceNames))
	copy(tmp, _ResourceNames)
	return tmp
}

var _ResourceMap = map[Resource]string{
	0: _ResourceName[0:4],
	1: _ResourceName[4:8],
}

// String implements the Stringer interface.
func (x Resource) String() string {
	if str, ok := _ResourceMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Resource(%d)", x)
}

var _ResourceValue = map[string]Resource{
	_ResourceName[0:4]:                  0,
	strings.ToLower(_ResourceName[0:4]): 0,
	_ResourceName[4:8]:                  1,
	strings.ToLower(_ResourceName[4:8]): 1,
}

// ParseResource attempts to convert a string to a Resource
func ParseResource(name string) (Resource, error) {
	if x, ok := _ResourceValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ResourceValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Resource(0), fmt.Errorf("%s is not a valid Resource, try [%s]", name, strings.Join(_ResourceNames, ", "))
}

// MarshalText implements the text marshaller method
func (x Resource) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Resource) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseResource(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var _ResourceErrNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Resource) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Resource(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Resource(v)
	case string:
		*x, err = ParseResource(v)
	case []byte:
		*x, err = ParseResource(string(v))
	case Resource:
		*x = v
	case int:
		*x = Resource(v)
	case *Resource:
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x = *v
	case uint:
		*x = Resource(v)
	case uint64:
		*x = Resource(v)
	case *int:
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x = Resource(*v)
	case *int64:
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x = Resource(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Resource(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x = Resource(*v)
	case *uint:
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x = Resource(*v)
	case *uint64:
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x = Resource(*v)
	case *string:
		if v == nil {
			return _ResourceErrNilPtr
		}
		*x, err = ParseResource(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Resource) Value() (driver.Value, error) {
	return x.String(), nil
}
