// Code generated by go-enum
// DO NOT EDIT!

package image

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// FormatJpeg is a Format of type Jpeg.
	FormatJpeg Format = iota
	// FormatPng is a Format of type Png.
	FormatPng
	// FormatGif is a Format of type Gif.
	FormatGif
	// FormatTiff is a Format of type Tiff.
	FormatTiff
	// FormatBmp is a Format of type Bmp.
	FormatBmp
)

const _FormatName = "jpegpnggiftiffbmp"

var _FormatNames = []string{
	_FormatName[0:4],
	_FormatName[4:7],
	_FormatName[7:10],
	_FormatName[10:14],
	_FormatName[14:17],
}

// FormatNames returns a list of possible string values of Format.
func FormatNames() []string {
	tmp := make([]string, len(_FormatNames))
	copy(tmp, _FormatNames)
	return tmp
}

var _FormatMap = map[Format]string{
	0: _FormatName[0:4],
	1: _FormatName[4:7],
	2: _FormatName[7:10],
	3: _FormatName[10:14],
	4: _FormatName[14:17],
}

// String implements the Stringer interface.
func (x Format) String() string {
	if str, ok := _FormatMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Format(%d)", x)
}

var _FormatValue = map[string]Format{
	_FormatName[0:4]:                    0,
	strings.ToLower(_FormatName[0:4]):   0,
	_FormatName[4:7]:                    1,
	strings.ToLower(_FormatName[4:7]):   1,
	_FormatName[7:10]:                   2,
	strings.ToLower(_FormatName[7:10]):  2,
	_FormatName[10:14]:                  3,
	strings.ToLower(_FormatName[10:14]): 3,
	_FormatName[14:17]:                  4,
	strings.ToLower(_FormatName[14:17]): 4,
}

// ParseFormat attempts to convert a string to a Format
func ParseFormat(name string) (Format, error) {
	if x, ok := _FormatValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _FormatValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Format(0), fmt.Errorf("%s is not a valid Format, try [%s]", name, strings.Join(_FormatNames, ", "))
}

// MarshalText implements the text marshaller method
func (x Format) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Format) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseFormat(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var _FormatErrNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Format) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Format(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Format(v)
	case string:
		*x, err = ParseFormat(v)
	case []byte:
		*x, err = ParseFormat(string(v))
	case Format:
		*x = v
	case int:
		*x = Format(v)
	case *Format:
		if v == nil {
			return _FormatErrNilPtr
		}
		*x = *v
	case uint:
		*x = Format(v)
	case uint64:
		*x = Format(v)
	case *int:
		if v == nil {
			return _FormatErrNilPtr
		}
		*x = Format(*v)
	case *int64:
		if v == nil {
			return _FormatErrNilPtr
		}
		*x = Format(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Format(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return _FormatErrNilPtr
		}
		*x = Format(*v)
	case *uint:
		if v == nil {
			return _FormatErrNilPtr
		}
		*x = Format(*v)
	case *uint64:
		if v == nil {
			return _FormatErrNilPtr
		}
		*x = Format(*v)
	case *string:
		if v == nil {
			return _FormatErrNilPtr
		}
		*x, err = ParseFormat(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Format) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// QualityHigh is a Quality of type High.
	QualityHigh Quality = iota
	// QualityMedium is a Quality of type Medium.
	QualityMedium
	// QualityLow is a Quality of type Low.
	QualityLow
)

const _QualityName = "highmediumlow"

var _QualityNames = []string{
	_QualityName[0:4],
	_QualityName[4:10],
	_QualityName[10:13],
}

// QualityNames returns a list of possible string values of Quality.
func QualityNames() []string {
	tmp := make([]string, len(_QualityNames))
	copy(tmp, _QualityNames)
	return tmp
}

var _QualityMap = map[Quality]string{
	0: _QualityName[0:4],
	1: _QualityName[4:10],
	2: _QualityName[10:13],
}

// String implements the Stringer interface.
func (x Quality) String() string {
	if str, ok := _QualityMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Quality(%d)", x)
}

var _QualityValue = map[string]Quality{
	_QualityName[0:4]:                    0,
	strings.ToLower(_QualityName[0:4]):   0,
	_QualityName[4:10]:                   1,
	strings.ToLower(_QualityName[4:10]):  1,
	_QualityName[10:13]:                  2,
	strings.ToLower(_QualityName[10:13]): 2,
}

// ParseQuality attempts to convert a string to a Quality
func ParseQuality(name string) (Quality, error) {
	if x, ok := _QualityValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _QualityValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Quality(0), fmt.Errorf("%s is not a valid Quality, try [%s]", name, strings.Join(_QualityNames, ", "))
}

// MarshalText implements the text marshaller method
func (x Quality) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Quality) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseQuality(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var _QualityErrNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Quality) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Quality(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Quality(v)
	case string:
		*x, err = ParseQuality(v)
	case []byte:
		*x, err = ParseQuality(string(v))
	case Quality:
		*x = v
	case int:
		*x = Quality(v)
	case *Quality:
		if v == nil {
			return _QualityErrNilPtr
		}
		*x = *v
	case uint:
		*x = Quality(v)
	case uint64:
		*x = Quality(v)
	case *int:
		if v == nil {
			return _QualityErrNilPtr
		}
		*x = Quality(*v)
	case *int64:
		if v == nil {
			return _QualityErrNilPtr
		}
		*x = Quality(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Quality(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return _QualityErrNilPtr
		}
		*x = Quality(*v)
	case *uint:
		if v == nil {
			return _QualityErrNilPtr
		}
		*x = Quality(*v)
	case *uint64:
		if v == nil {
			return _QualityErrNilPtr
		}
		*x = Quality(*v)
	case *string:
		if v == nil {
			return _QualityErrNilPtr
		}
		*x, err = ParseQuality(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Quality) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// ResizeModeFit is a ResizeMode of type Fit.
	ResizeModeFit ResizeMode = iota
	// ResizeModeFill is a ResizeMode of type Fill.
	ResizeModeFill
)

const _ResizeModeName = "fitfill"

var _ResizeModeNames = []string{
	_ResizeModeName[0:3],
	_ResizeModeName[3:7],
}

// ResizeModeNames returns a list of possible string values of ResizeMode.
func ResizeModeNames() []string {
	tmp := make([]string, len(_ResizeModeNames))
	copy(tmp, _ResizeModeNames)
	return tmp
}

var _ResizeModeMap = map[ResizeMode]string{
	0: _ResizeModeName[0:3],
	1: _ResizeModeName[3:7],
}

// String implements the Stringer interface.
func (x ResizeMode) String() string {
	if str, ok := _ResizeModeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ResizeMode(%d)", x)
}

var _ResizeModeValue = map[string]ResizeMode{
	_ResizeModeName[0:3]:                  0,
	strings.ToLower(_ResizeModeName[0:3]): 0,
	_ResizeModeName[3:7]:                  1,
	strings.ToLower(_ResizeModeName[3:7]): 1,
}

// ParseResizeMode attempts to convert a string to a ResizeMode
func ParseResizeMode(name string) (ResizeMode, error) {
	if x, ok := _ResizeModeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ResizeModeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ResizeMode(0), fmt.Errorf("%s is not a valid ResizeMode, try [%s]", name, strings.Join(_ResizeModeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x ResizeMode) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *ResizeMode) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseResizeMode(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var _ResizeModeErrNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ResizeMode) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ResizeMode(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = ResizeMode(v)
	case string:
		*x, err = ParseResizeMode(v)
	case []byte:
		*x, err = ParseResizeMode(string(v))
	case ResizeMode:
		*x = v
	case int:
		*x = ResizeMode(v)
	case *ResizeMode:
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x = *v
	case uint:
		*x = ResizeMode(v)
	case uint64:
		*x = ResizeMode(v)
	case *int:
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x = ResizeMode(*v)
	case *int64:
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x = ResizeMode(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = ResizeMode(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x = ResizeMode(*v)
	case *uint:
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x = ResizeMode(*v)
	case *uint64:
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x = ResizeMode(*v)
	case *string:
		if v == nil {
			return _ResizeModeErrNilPtr
		}
		*x, err = ParseResizeMode(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x ResizeMode) Value() (driver.Value, error) {
	return x.String(), nil
}
