// Code generated by ent, DO NOT EDIT.

package uservolume

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the uservolume type in the database.
	Label = "user_volume"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldVolumeID holds the string denoting the volume_id field in the database.
	FieldVolumeID = "volume_id"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldWrite holds the string denoting the write field in the database.
	FieldWrite = "write"
	// FieldDelete holds the string denoting the delete field in the database.
	FieldDelete = "delete"
	// FieldShare holds the string denoting the share field in the database.
	FieldShare = "share"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeVolume holds the string denoting the volume edge name in mutations.
	EdgeVolume = "volume"
	// UserFieldID holds the string denoting the ID field of the User.
	UserFieldID = "id"
	// VolumeFieldID holds the string denoting the ID field of the Volume.
	VolumeFieldID = "id"
	// Table holds the table name of the uservolume in the database.
	Table = "user_volumes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_volumes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// VolumeTable is the table that holds the volume relation/edge.
	VolumeTable = "user_volumes"
	// VolumeInverseTable is the table name for the Volume entity.
	// It exists in this package in order to avoid circular dependency with the "volume" package.
	VolumeInverseTable = "volumes"
	// VolumeColumn is the table column denoting the volume relation/edge.
	VolumeColumn = "volume_id"
)

// Columns holds all SQL columns for uservolume fields.
var Columns = []string{
	FieldUserID,
	FieldVolumeID,
	FieldRead,
	FieldWrite,
	FieldDelete,
	FieldShare,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultWrite holds the default value on creation for the "write" field.
	DefaultWrite bool
	// DefaultDelete holds the default value on creation for the "delete" field.
	DefaultDelete bool
	// DefaultShare holds the default value on creation for the "share" field.
	DefaultShare bool
)

// OrderOption defines the ordering options for the UserVolume queries.
type OrderOption func(*sql.Selector)

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByVolumeID orders the results by the volume_id field.
func ByVolumeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVolumeID, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByWrite orders the results by the write field.
func ByWrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWrite, opts...).ToFunc()
}

// ByDelete orders the results by the delete field.
func ByDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelete, opts...).ToFunc()
}

// ByShare orders the results by the share field.
func ByShare(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShare, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByVolumeField orders the results by volume field.
func ByVolumeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVolumeStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, UserColumn),
		sqlgraph.To(UserInverseTable, UserFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newVolumeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, VolumeColumn),
		sqlgraph.To(VolumeInverseTable, VolumeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, VolumeTable, VolumeColumn),
	)
}
