version: 3

env:
  TOOLS_BIN:
    sh: echo "$(pwd)/bin"

tasks:
  all:
    desc: Install build dependencies
    cmds:
      - task: standard-version
      - task: commitlint

  standard-version:
    deps: [install-js-deps]
  commitlint:
    deps: [install-js-deps]


  install-js-deps:
    vars:
      PWD:
        sh: pwd
    cmds:
      - yarn install --frozen-lockfile
      - ln -sf {{.PWD}}/node_modules/.bin/standard-version {{.PWD}}/bin/standard-version
      - ln -sf {{.PWD}}/node_modules/.bin/commitlint {{.PWD}}/bin/commitlint
    sources:
      - package.json
      - yarn.lock
    generates:
      - bin/standard-version
      - bin/commitlint
