// Code generated by ent, DO NOT EDIT.

package groupvolume

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the groupvolume type in the database.
	Label = "group_volume"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldVolumeID holds the string denoting the volume_id field in the database.
	FieldVolumeID = "volume_id"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldWrite holds the string denoting the write field in the database.
	FieldWrite = "write"
	// FieldDelete holds the string denoting the delete field in the database.
	FieldDelete = "delete"
	// FieldShare holds the string denoting the share field in the database.
	FieldShare = "share"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeVolume holds the string denoting the volume edge name in mutations.
	EdgeVolume = "volume"
	// GroupFieldID holds the string denoting the ID field of the Group.
	GroupFieldID = "id"
	// VolumeFieldID holds the string denoting the ID field of the Volume.
	VolumeFieldID = "id"
	// Table holds the table name of the groupvolume in the database.
	Table = "group_volumes"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "group_volumes"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// VolumeTable is the table that holds the volume relation/edge.
	VolumeTable = "group_volumes"
	// VolumeInverseTable is the table name for the Volume entity.
	// It exists in this package in order to avoid circular dependency with the "volume" package.
	VolumeInverseTable = "volumes"
	// VolumeColumn is the table column denoting the volume relation/edge.
	VolumeColumn = "volume_id"
)

// Columns holds all SQL columns for groupvolume fields.
var Columns = []string{
	FieldGroupID,
	FieldVolumeID,
	FieldRead,
	FieldWrite,
	FieldDelete,
	FieldShare,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultWrite holds the default value on creation for the "write" field.
	DefaultWrite bool
	// DefaultDelete holds the default value on creation for the "delete" field.
	DefaultDelete bool
	// DefaultShare holds the default value on creation for the "share" field.
	DefaultShare bool
)

// OrderOption defines the ordering options for the GroupVolume queries.
type OrderOption func(*sql.Selector)

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByVolumeID orders the results by the volume_id field.
func ByVolumeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVolumeID, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByWrite orders the results by the write field.
func ByWrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWrite, opts...).ToFunc()
}

// ByDelete orders the results by the delete field.
func ByDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelete, opts...).ToFunc()
}

// ByShare orders the results by the share field.
func ByShare(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShare, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByVolumeField orders the results by volume field.
func ByVolumeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVolumeStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, GroupColumn),
		sqlgraph.To(GroupInverseTable, GroupFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newVolumeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, VolumeColumn),
		sqlgraph.To(VolumeInverseTable, VolumeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, VolumeTable, VolumeColumn),
	)
}
