// Code generated by ent, DO NOT EDIT.

package groupvolume

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/filebrowser/filebrowser/backend/storage/ent/predicate"
)

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldGroupID, v))
}

// VolumeID applies equality check predicate on the "volume_id" field. It's identical to VolumeIDEQ.
func VolumeID(v int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldVolumeID, v))
}

// Read applies equality check predicate on the "read" field. It's identical to ReadEQ.
func Read(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldRead, v))
}

// Write applies equality check predicate on the "write" field. It's identical to WriteEQ.
func Write(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldWrite, v))
}

// Delete applies equality check predicate on the "delete" field. It's identical to DeleteEQ.
func Delete(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldDelete, v))
}

// Share applies equality check predicate on the "share" field. It's identical to ShareEQ.
func Share(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldShare, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNotIn(FieldGroupID, vs...))
}

// VolumeIDEQ applies the EQ predicate on the "volume_id" field.
func VolumeIDEQ(v int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldVolumeID, v))
}

// VolumeIDNEQ applies the NEQ predicate on the "volume_id" field.
func VolumeIDNEQ(v int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNEQ(FieldVolumeID, v))
}

// VolumeIDIn applies the In predicate on the "volume_id" field.
func VolumeIDIn(vs ...int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldIn(FieldVolumeID, vs...))
}

// VolumeIDNotIn applies the NotIn predicate on the "volume_id" field.
func VolumeIDNotIn(vs ...int) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNotIn(FieldVolumeID, vs...))
}

// ReadEQ applies the EQ predicate on the "read" field.
func ReadEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldRead, v))
}

// ReadNEQ applies the NEQ predicate on the "read" field.
func ReadNEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNEQ(FieldRead, v))
}

// WriteEQ applies the EQ predicate on the "write" field.
func WriteEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldWrite, v))
}

// WriteNEQ applies the NEQ predicate on the "write" field.
func WriteNEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNEQ(FieldWrite, v))
}

// DeleteEQ applies the EQ predicate on the "delete" field.
func DeleteEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldDelete, v))
}

// DeleteNEQ applies the NEQ predicate on the "delete" field.
func DeleteNEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNEQ(FieldDelete, v))
}

// ShareEQ applies the EQ predicate on the "share" field.
func ShareEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldEQ(FieldShare, v))
}

// ShareNEQ applies the NEQ predicate on the "share" field.
func ShareNEQ(v bool) predicate.GroupVolume {
	return predicate.GroupVolume(sql.FieldNEQ(FieldShare, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupVolume {
	return predicate.GroupVolume(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, GroupColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupVolume {
	return predicate.GroupVolume(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVolume applies the HasEdge predicate on the "volume" edge.
func HasVolume() predicate.GroupVolume {
	return predicate.GroupVolume(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, VolumeColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, VolumeTable, VolumeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVolumeWith applies the HasEdge predicate on the "volume" edge with a given conditions (other predicates).
func HasVolumeWith(preds ...predicate.Volume) predicate.GroupVolume {
	return predicate.GroupVolume(func(s *sql.Selector) {
		step := newVolumeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupVolume) predicate.GroupVolume {
	return predicate.GroupVolume(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupVolume) predicate.GroupVolume {
	return predicate.GroupVolume(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupVolume) predicate.GroupVolume {
	return predicate.GroupVolume(sql.NotPredicates(p))
}
